CodeYourFuture/curriculum

config.toml
Bugfix
config had syllabus as root so pull from github was not working
note: I will likely abstract this out of the templates at some point
=> changed root from syllabus to curriculum

layouts/partials/page-header.html
we never want an empty toc printing over a populated one! 
given a day plan or prep page
when the page content is over 400 words
print the auto TOC before the block toc
given a day plan or prep page
when there are 1 or fewer blocks
do not show the TOC
=> combine the two Tocs

create_module.sh
add label filter to main module backlog
existing modules will need to be manually updated
empty modules can be re-created
check on Module-Databases / backlog to see problem and resolution
this depends on adding the module label to issues, so may also need to check this is created by default on coursework issue forms (I think it is)
=> Filter out PRs and bug reports on backlog

assets/scripts/cm6.ts, assets/scripts/highlight-lines.ts, layouts/_default/_markup/render-codeblock-js.html, layouts/partials/foot.html
Highlight specific lines of a code block when using CM6. This was raised as a feature request in https://github.com/CodeYourFuture/curriculum/issues/9.
I also took the liberty of converting the CM6 code to TypeScript. This is mostly because CM6 itself is written in TS, as is most of the documentation, and so it makes sense to follow that. Frustratingly I still get a type error in VSCode, but it's spurious (at least in browsers that aren't 10+ years old). Hints on how to get rid of this would be welcome.
@Dedekind561 @SallyMcGrath since you requested it :D
=> Highlight lines in CM6

layouts/_default/success.html, layouts/partials/block-data.html, layouts/partials/block-readme.html, layouts/partials/objectives-lookup.html, layouts/partials/objectives-parsed.html
Module: all
Week(s): all / success pages
- [ x] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [ x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [x ] I have run my code to check it works
- [x ] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)
I know I must be stopped - I really did want all this as modules instead but it just doesn't work, so here I am writing 40 line templates. I'm sorry :/ 
this code grabs anything marked up as objectives eg …
=> Feature: compile and extract objectives from github

README.md
If you don't `npm i` first, you get errors about missing npm modules.
=> Add `npm i` as part of "to run locally"

assets/scripts/highlight-lines.ts
Module: N/A
Week(s): N/A
Fixes CM6 codeblocks without highlights that were throwing an error.
=> Fix CM6 highlight lines throwing

layouts/partials/block-data.html
so we can access the .Section
https://gohugo.io/variables/page/#section-variables-and-methods
Local blocks had disappeared since I refactored the block data
For ex fundamentals/sprints/1/day-plan/#user-stories were blank
This was because the .Page object belongs to the scope, so when passing the scope in this way we need to do $variable.Page.Section - we can't do $variable.Section as $variable is not .Page in this context.
I would like to further refactor this but so many PRs are building up I am loath to do more there. Will leave until Search has been looked at.
=> pass the page object correctly to local blocks

layouts/_default/_markup/render-image.html, layouts/_default/_markup/render-link.html
Module: all
Week(s): all
I used this example to build this: https://github.com/bep/portable-hugo-links
Improving link handling to remove/reduce dependency on Hugo shortcodes (which won't work or show up on Github). It's not actually wikilinks [[]] but plain md links without using https://gohugo.io/content-management/shortcodes/#ref-and-relref
This necessitated also some rework of the image render hook so I improved that quite a lot as well. This feature depends on the local-block bugfix pr as it's all about links and destinations. #43 
Using this feature now you should be able to use relative links and assume hugo will figure stuff out. This means that writing, for example, in 
content/blocks/telephone
you can write [Prep](databases/prep)
and then if you show that content on, say, …
=> Feature: Wikilinks (sorta_

content/fundamentals/prep/index.md
Week(s): Prep
Adds an explicit reference to the "What is GitHub" tab on the Fundamentals prep page, to make the tab more obvious and prevent it from being missed.
Discussed  in https://github.com/CodeYourFuture/curriculum/issues/54#issuecomment-1586124881. I'll defer to Sally on how to visually punch up the tab though.
@SallyMcGrath 
@illicitonion
=> Explicitly reference the What Is GitHub tab

layouts/_default/_markup/render-codeblock-objectives.html
Module: all
Week(s): all
addresses #45
I don't think we should try to hijack task lists here, but fix the markup in GFM - I opened an issue about it some time ago anyway
But we can mark up task lists as objectives pretty easily so let's do that?
=> Feature: pass objectives to objective block

layouts/partials/block-pd.html, layouts/partials/block-readme.html, layouts/partials/byline.html
so we don't get an empty heading and a ragged right
this isn't the revision I want to do, this is just a bugfix so it doesn't look actually broken
fixes #64
=> only show byline when it exists

layouts/partials/block-data.html, layouts/partials/block-issue.html, layouts/partials/block-local.html, layouts/partials/block-pd.html, layouts/partials/block-readme.html, layouts/partials/time.html
we only want to show minutes on prep and dayplan layouts I think?
make a time partial and call it in some circumstances, eg on scheduling views
addresses #58
does not resolve all the block header things i have issues with
=> Revision: remove spurious minutes

assets/scripts/app.js
I was loath to do this and I have built in a way to mark up task lists as objectives (to feed them to other views) but I guess actually we also want task lists that are not objectives so here we are - I have just fixed it post hoc with a link in the code to the issue -- when GFM fix this we can remove our js.
https://github.com/github/cmark-gfm/issues/299
=> temporary fix for GFM task lists

layouts/partials/issues.html
I have edited all the issues.
We will now rely on notifications of build/deploy failures to detect these problems in the future.
We should probably work out who gets those notifications.
Fixes #59
=> Error instead of warning on `_No response_`

assets/styles/04-components/copy.scss, layouts/partials/block/pd.html
https://github.com/gohugoio/hugo/issues/7372
If the text is just one line, markdownify doesn't give us paragraphs, or a way to tell if this is the case. In the PD blocks we quite often get this.
I am constraining phrasing blocks to a readable line length, so this choice has some text spooling out across the page
Therefore I have begrudgingly wrapped these risk areas in a div and constrained that.
But I don't like it
=> markdownify is sometimes weird

layouts/_default/success.html, layouts/partials/objectives/lookup.html, layouts/partials/objectives/parsed.html
1. make heading invisible as per feedback
2. get local module objectives:  the section was empty
3. only show headings if objectives exist: PD was printing empty blocks
fixes #73 
I feel like we could do a lot more with this page but let's just put it out there and see what users do first
=> revise success page

layouts/partials/head.html
the load was too fast for the loading animation and LCP was not registered. This actually makes no difference to the user but it will trigger an error in LIghthouse
=> performance tweak for LCP

content/fundamentals/blocks/ship-it-iteration/index.md
Week(s): 1
VSCode doesn't show previews by default (as was expected from https://syllabus.codeyourfuture.io/fundamentals/week-2/session#step-by-step
- though maybe we used to have trainees install extensions earlier or something? I couldn't find where, if so...)
So instead have the trainees explicitly install an extension.
Follow up from #116
=> Fix previewing instructions in Fundamentals 2 Ship It

content/blocks/backlog/index.md
obviously this should be a better fix but we are going live tomorrow
the backlog link doesn't find the backlog - it should be relative but Hugo relative link doesn't seem to find it and neither does our wikilinkish render hook. Not sure why, and it will be interesting to find out, but for now I've just removed the broken link.
=> temp fix for backlog link

layouts/partials/scripts.html
temporarily load scripts until we track down this page store problem
https://discourse.gohugo.io/t/page-store-is-sometimes-empty-for-unclear-reasons/44950
I will revert this ASAP because we never want to load all scripts on every page, except obviously in this case we must get something working for tomorrow
Addresses #143 and #145
=> TEMPORARY FIX for missing scripts

layouts/partials/block/data.html, layouts/partials/block/youtube.html, layouts/shortcodes/tab.html, layouts/shortcodes/tabs.html, layouts/shortcodes/youtube.html
This is a bugfix but also a feature change tbh as it takes out a bunch of (unused) functionality 
I know we've all pointed it out, I can't find the issue for it!
-[x] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)
I have made these changes:
In the youtube shortcode partial, 
which is a pass-through that calls the youtube block, I have also passed along the context that this is a shortcode by adding it to the blockData. I didn't add it to the page scratch as I thought it might get messy with multiple versions of this block on the page, some shortcode some not.
You can test this on fundamentals/prep/ which has a video in a tab up top and then an inline video down the page. The inline video has a (visually hidden) heading and the tab video …
=> Feature : nestable Youtube shortcode, in new tabs

layouts/partials/block/data.html, layouts/partials/block/readme.html
all
1. Bump the time to 120 minutes as default on workshops as that's how long they are being schedule for in class
2. Parse out stuff in html comments on github readme -- this can be used to use fancy hugo markup in github without making it look weird on github
I've done this in the Devtools workshop
TODO: the next thing to do would be to send over commented out front matter and transform it like we do in the pd block. I can't really get this working at the moment and I don't think it's worth holding up these changes.
=> Feature: comments on github become hugo shortcodes

layouts/_default/_markup/render-image.html
Module: all
Week(s):
I want to hotlink github images and it's blocking me so I'm going round it with jsDelivr. Take that, CORS.
Longer term, I'd prefer we had a regular action to go get these images and process them with Hugo Pipes. Please write one!
=> Feature: add jsDelivr to get round CORS

assets/scripts/youtube-player.js, layouts/partials/block/data.html, layouts/partials/block/youtube.html
Module: all
Week(s):
I wanted to link to a specific video in a playlist, but then let the playlist roll. So I've extended the youtube component to do this.
While I was there, I moved all the string manipulation into the web component as it seems like it belongs to the youtube component. The string isn't used anywhere else.
=> Feature: Youtube Playlists

layouts/_default/success.html, layouts/partials/objectives/lookup.html
Module: all
Week(s): all
Addresses https://github.com/CodeYourFuture/curriculum/pull/188#discussion_r1271553416
Adds friendly titles to local blocks on success pages
@illicitonion
=> Feature: friendly titles on success page for local blocks

assets/styles/03-elements/headings.scss
Removes upper case off the h4 class. Personal preference here unless someone else thinks it should be capitalised?
=> remove text transform off e-heading_4 class

content/fundamentals/prep/index.md, layouts/shortcodes/tabs.html, layouts/shortcodes/youtube.html
1. Make tabs fully work with youtube shortcode
- 1. you have to declare the shortcode as safeHTML if you're nesting this deep but only sometimes so I've set it for all cases as this is always html
- 2. You have to actually set the boolean isShortcode to the scratch map instead of just somehow willing it with your mind
2. Store this one weird tip by [showing content change](https://github.com/CodeYourFuture/curriculum/pull/198/files#diff-e4a97e4548b6599d18a607fdde1c1fdb92273bab764dc55a2ad6ff3176a05b03)
If you use % markers in markdown in nested tabs your html will always be escaped, safeHTML or nay, so don't use those unless you want that, lesson learned
=> Bug: weird escaping markdownifying inner nested shortcodes

layouts/partials/block/local.html, layouts/partials/block/pd.html, layouts/partials/block/readme.html, layouts/partials/time.html
Currently the time render properly for workshops on the day plan.
Just tweaked the data passed to the time partial so it shows up properly.
Note: no time for the git workshop section.
https://deploy-preview-221--cyf-curriculum.netlify.app/induction/sprints/1/day-plan/#git-workshop
It should have the correct time and it should have a duration of 2 hours.
=> fix readme timestamp on day-plan schedule

assets/styles/04-components/tooltip.scss, layouts/shortcodes/tooltip.html
feature
There are lots of definitions making the prep views very long. Should some of them be tooltips? 
PS footnotes already exist in this flavour of markdown
https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/
I've actually lost preview as my user id has been temporarily rate limited on github. But this should roughly work?
=> Feature: basic tooltip

layouts/_default/_markup/render-image.html, layouts/shortcodes/tabs.html
Module: all
Week(s): all
So, once deeply nested inside tabs, image links coming from headless leaf bundles were broken. This is because at the point of render, markdownify didn't know where the hell it was.
I've used https://gohugo.io/functions/renderstring/ to control the site of the render, in tabs.html on line 27
and then accessed the global page object inside the image hook to find the resource on render_image line 24
I also updated the fall back to global check on 32, 33 to use the same get resources method and assume we put everything global in the assets dir . It's empty at the moment but obv I did stuff some images in there to check.
Note, this doesn't address the larger image handling changes we want to make, it just fixes the display problem thrown up in JS1-1
=> Bugfix: Images in Tabs

layouts/partials/issues.html
Module: all
Week(s): all
We hit this problem because PD added all their issues and we went to page 2.
I never want us to have more than 25 issues in a week (we're now about 10) so instead of doing a complicated "go to next page" request I've just set the pagination to 100.
=> Bugfix : issue response was paginating

assets/scripts/app.js
Module: all
Week(s): all
fixing #201
Given we turn on 
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable
We should then suppress
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck
and https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize
etc.
=> Bugfix : suppress spellcheckers

assets/styles/04-components/tooltip.scss
It wasn't super obvious to me at a glance that these were hoverable - this maybe makes that more obvious.
=> Underline tooltip text

content/html-css/success/index.md, layouts/_default/success.html
Module: each, but example is in HTML-CSS
Week(s): all /4
Creates a different success view for the module level
This view expects objectives to be directly set in the md 
Addresses #266
=> Feature: Module Success

content/html-css/product/_index.md, content/html-css/product/build/index.md, content/html-css/product/plan/index.md, content/html-css/product/ship/index.md, content/html-css/product/test/index.md, layouts/_default/single.html
Module: HTML-CSS
Week(s): 1-4
1. I connected the module project issues as block calls to the product pages
2. Probably for JS1 we will want a repo with plan/build/test/ship as folders with readmes instead but this seems ok for this module
3. Doing this exposed that I failed to update the block call in single.html, the layout all singles fall back to if they don't have a named layout, so I fixed that path ( I have a zillion PRs open so I'm not splitting it out as I caused confusion last time, though I do think content and features should be separate ideally...)
=> Content: HTML module project

layouts/partials/block/data.html
=> remove default time of 120 for workshops

content/js1/blocks/percentages/index.md
Module: JS1
Week(s): 2
I don't think it's super clear that trainees are expected to put in placeholder values, and the SyntaxError they'll get if they copy + paste the code as-is doesn't seem to have great learning value.
=> Make example code valid

layouts/partials/block/pullreq.html
This should hopefully prevent trainees from thinking that they need to review the PRs
Module: N/A
Week(s): N/A
Add some text to the PR block to explain that the PRs are to be reviewed by volunteers, not trainees.
=> Add explanatory text to PR block

content/fundamentals/blocks/code-dot-org/index.md, content/fundamentals/blocks/cyf-blocks-requirements/index.md, content/fundamentals/blocks/overcoming-blockers/index.md, content/fundamentals/blocks/user-stories/index.md, content/fundamentals/blocks/using-the-curriculum/index.md, content/fundamentals/sprints/1/day-plan/index.md, content/fundamentals/sprints/2/prep/index.md
Week(s): 1 & 2
This PR introduces "Using the curriculum" presentation to week 1 of Fundamentals. It is a set of activities that will invite volunteers and trainees to navigate the curriculum and make sense of how to use it at CYF.
"Using the curriculum" is the first of two workshops inviting people to make sense of the CYF curriculum. The second one occurs at the start of the SDC in Induction and is a discussion about the challenges of using the curriculum.
The blockly based content is now set as prep for week 2 of Fundamentals.
[Fundamentals sprint 1 day plan](https://deploy-preview-305--cyf-curriculum.netlify.app/fundamentals/sprints/1/day-plan/)
[Fundamentals sprint 2 prep](https://deploy-preview-305--cyf-curriculum.netlify.app/fundamentals/sprints/2/prep/)
=> Add Using the curriculum to Fundamentals

content/js2/_index.md, content/js2/blocks/check-in/index.md, content/js2/blocks/demo/index.md, content/js2/blocks/pair-up/index.md, content/js2/blocks/pick-an-app/index.md, content/js2/sprints/1/day-plan/index.md, content/js2/sprints/2/day-plan/index.md, content/js2/sprints/3/day-plan/index.md, content/js2/sprints/3/prep/index.md, content/js2/sprints/4/day-plan/index.md
=> add day plans for JS2

layouts/_default/_markup/render-image.html
Addresses #333
I haven't put it as an error (which will fail the build) because the nature of this platform is that we will be pulling in UGC from many places and we won't have control of all the markdown. I don't want to throw errors a contributor cannot fix.
You can't exit a render hook with a warning, so I've placed a check at the start for empty .Destination and printed a warning to the console.
Ive created a broken image in an issue here
https://github.com/CodeYourFuture/Module-Template/issues/6
You can pull it in as a block to see the page build with no image (not even broken in this case, which we can argue about if you like...)
```
[[blocks]]
name="MRE broken image"
src="https://github.com/CodeYourFuture/Module-Template/issues/6"
```
=> Bugfix warn on empty markdown

layouts/partials/issues.html
addresses #333
1. improve api call to only pull open issues not all issues and PRs
2. rm template check on state as it's available as an argument
I've kept the partial match on labels as I just don't remotely trust us to be disciplined with labelling as we are many part time humans not one hive mind
compare https://deploy-preview-334--cyf-curriculum.netlify.app/html-css/sprints/1/backlog/ to  https://github.com/orgs/CodeYourFuture/projects/87/views/4
=> filter api call to only look at issues

content/html-css/sprints/3/day-plan/index.md
Module: HTML CSS
Week(s): 3
add correct time to get forms workshop
=> fix get forms time html css sprint 3

.github/pull_request_template.md
The PR template
Removes the "Rendered Pages" section of the PR template. Pretty sure the bot referenced here has been superseded by the netlify bot.
=> Remove unused rendered pages section

config.toml, layouts/partials/issues.html, layouts/shortcodes/contributors.html
Previously we were just missing any issues that didn't happen to
paginate on the first page.
For JS3, this was quite a few issues.
=> List issues via a pagination-expanding proxy

content/js2/success/index.md, content/js3/_index.md, content/js3/blocks/break-down/index.md, content/js3/blocks/capturing-events/index.md, content/js3/blocks/components/index.md, content/js3/blocks/composing-elements/index.md, content/js3/blocks/now-showing/index.md, content/js3/blocks/one-to-one/index.md, content/js3/blocks/re-rendering-ui/index.md, content/js3/blocks/reacting/index.md, content/js3/blocks/single-datum/index.md, content/js3/blocks/updating-state/index.md, content/js3/blocks/using-map/index.md, content/js3/prep/index.md, content/js3/sprints/2/prep/index.md, content/js3/sprints/3/prep/index.md, content/js3/success/index.md, static/filterFilms.html
Module: JS3
Week(s): 1, 2
I have revised week 1 to remove innerHTMl. To make this readable I have introduced template HTML. To follow on with this, I've moved week 3 to week2 as per the discussion here https://github.com/CodeYourFuture/curriculum/discussions/315
They define a template, they define a state object, they update the state based on interactions, the UI reacts to the state -- the UI is a function of the state 
It's going to be taught really soon so this will have to be deployed this week regardless and revisions will be done on the deployed pages.
=> Content: Revise and Reorder JS3 1 and 2

assets/styles/04-components/columns.scss, layouts/shortcodes/columns.html
Module: JS3
Week(s): 3
this tiny feature adds columns as a shortcode in markdow
=> Feature: columns shortcode (tiny)

content/js3/sprints/3/day-plan/index.md
Module: JS3
Week(s): 3
Dayplan for JS3 with debugging workshop, that must be merged before this one can be https://github.com/CodeYourFuture/CYF-Workshops/pull/164 
Please review that workshop and merge it, then merge this one . This PR is blocked by https://github.com/CodeYourFuture/CYF-Workshops/pull/164
=> day plan with proposed workshop

config.toml
we don't need to redirect inside the language unless we are producing sites
so I've removed the config of baseURL inside the /en config 
so assets will work again on your local
=> do not overwrite baseURL

assets/styles/03-elements/table.scss, layouts/_default/_markup/render-codeblock-runkit.html
Module: Node + all
Week(s): all
The Express docs use this and it's pretty easy to create notebooks directly from a render hook.
https://runkit.com/home
It's not themeable, really, so far as I can see. Sadface. But you can do this:
- all documents on RunKit are public, you can make them searchable by publishing.
- all of npm's 1,000,000+ packages are already pre-installed, just require() them
- use arrow functions, classes, template strings, and most of ES6. See everything we support here.
- await any promise instead of using callbacks (example)
- store secrets in environment variables
- export an endpoint function to turn any notebook into an API (endpoint docs)
```runkit
//Load the 'express' library to easily handle HTTP conversations:
const express = require("express");
const app = …
```
=> Feature: Runkit -- I want executable runkits for Node

assets/scripts/solo-view.js, content/en/html-css/sprints/1/prep/index.md, layouts/_default/prep.html
Module: HTML
Week(s): 1, 2, 3
The solo view was selecting blocks inside blocks and this meant the block index and the block array were mismatched
I have updated the component to limit the selector to the scope we actually want
In the course of tracking down this bug, I made a bunch of improvements to this and a few other web components, but I will open those as a new PR
=> Bugfix: blank views on prep pages

assets/scripts/youtube-player.js
An example video with a caption: 
`yourlocalhost/induction/sprints/1/day-plan/`
=> Update youtube query params for captions (#410, #230)

README.md, assets/styles/04-components/tooltip.scss
Minor change to update the README to point people to use dotenv instead supplying secret values on the command line. The `dotenv` command while non standard is included in the `package.json` so is installed using `npm i`
=> Update README to point users to use dotenv

assets/styles/03-elements/images.scss, content/en/react/prep/index.md, layouts/partials/block/block.html, layouts/partials/block/data.html, layouts/partials/block/slide.html
Module: all
Week(s): all
I made a slide block. You can use it to set up slide decks with solo view or just intersperse hero images. At the moment it's just assuming you're linking a single image - though obviously you could expand this.
I made it purely because I want to put some good pictures I found in the React module, but I don't want them on the page with text. I want them solo. I could just make a local content block for each and include this single image, but it felt sufficiently distinguished to become a block.  
In this case I reconstruct the markdown for a figure and send it to the existing render hook for images. 
It expects
```
name="the usual heading, and you could hide this"
src="https://github.com/MaggieAppleton/react-metaphors-slides/blob/master/PNGs/MetaphorsofReact_2.0.01 …
```
=> add new slide block type

content/en/js1/sprints/4/prep/index.md, content/en/js2/sprints/1/prep/index.md
Module: JS1 Week 4, JS2 Week 1
Add step-through-prep workshops ( recordings of sessions with WM5 trainees on the prep view )
[JS2 Week 1 prep view](https://deploy-preview-514--cyf-curriculum.netlify.app/js2/sprints/1/prep/)
[JS1 Week 4 prep view](https://deploy-preview-514--cyf-curriculum.netlify.app/js1/sprints/4/prep/)
=> add step-through-prep workshops

content/en/databases/sprints/4/prep/index.md
=> Update index Prep DB/SQL S4 PD.md

.github/pull_request_template.md
=> add major change warning, see below

archetypes/backlog.md, archetypes/blocks/index.md, archetypes/day-plan.md, archetypes/default.md, archetypes/module-prep.md, archetypes/module-success.md, archetypes/module.md, archetypes/prep.md, archetypes/product-backlog.md, archetypes/product-prep.md, archetypes/product.md, archetypes/sprint.md, archetypes/success.md, create_module.sh
This moves page creation into Hugo archetypes. You can still run a create_module.sh to produce a module all at once, it will just do it by calling archetypes. You can also generate any individual view from an archetype, and generate a block, with hugo new --kind
https://gohugo.io/content-management/archetypes/
This is necessary for the modularisation change upcoming. #421
=> archetypes for all required module views

content/en/js2/sprints/2/prep/index.md, content/en/js2/sprints/3/prep/index.md, content/en/js3/sprints/3/prep/index.md
Module: JS2 Week 2, Week 3 & JS3 Week 3
Add step through prep workshops for JS2 Week 2, JS2 Week 3, JS3 Week 3. Each of the prep views below should have a step -> prep block:
[JS3 Sprint …
=> add step -> prep workshops for JS2 & JS3

.github/workflows/check-consistency.yml, .github/workflows/test-tooling.yml, tooling/go/.gitignore, tooling/go/cmd/local-overrides-enforcer/main.go, tooling/go/go.mod, tooling/go/go.sum, tooling/go/internal/local-overrides-enforcer/checker/checker.go, tooling/go/internal/local-overrides-enforcer/checker/checker_test.go
Daniel's tooling with path changed from curriculum-labs to curriculum
no other changes
Co-authored by daniel@codeyourfuture.io
=> Feature: Daniel's tooling for local module replacements

org-cyf/content/js3/sprints/1/prep/index.md, org-cyf/content/js3/sprints/2/prep/index.md
Module: JS3
Week(s): Sprint 1 & 2
Restores prep workshops to JS3 Sprint 1 & 2
=> restore js3 prep workshops

common-theme/hugo.toml
Module: all
Week(s): all
#548 
The videos in tabs are not showing up because the inner content of tabs is not being escaped . It seems like this is because the markdown settings are not set as the hugo.toml for common-theme is missing. Either I deleted it by mistake or created it wrong when I redid the modularisation. I didn't copy my work, I recreated it, to make sure I understood my process clearly. 
I want to push this file up to see the effects on the local curriculum build.
=> common-theme is missing its config

.env.example, README.md, org-cyf/README.md, org-cyf/package.json, org-mcb/package.json
The GITHUB TOKEN's environment name has changed recently but this was not reflected in the readme and the .env configs. This change also makes sure that the .env file values are proeprly picked up, and that the README is updated to help new users be able to set up their local dev environment quicker
=> Fix environment setup in new structure

common-content/en/blocks/evaluate/index.md, org-cyf/content/js3/sprints/1/day-plan/index.md
=> add evaluate block

common-content/en/blocks/morning-orientation/index.md, common-theme/assets/styles/03-elements/misc-phrasing.scss, org-cyf/content/react/sprints/1/day-plan/index.md, org-cyf/content/react/sprints/2/day-plan/index.md, org-cyf/content/react/sprints/3/day-plan/index.md, org-cyf/content/react/sprints/4/day-plan/index.md
Module: React day plans
Week(s): 1 2 3 4 
Also morning-orientation block, which I have added to every week on this day plan and therefore looked at more and simplified it -- it was a bit baggy.
Nobody reviewed the React workshops and they languished for 6 weeks. WM5 is approaching so I have merged them. They are just the pokedex workshops from the old syllabus, so not new material. However, if anyone has edits please open prs to cyf-workshops!
=> Content: React workshops on day plans plus simplified orientation block

org-cyf/content/servers/sprints/3/day-plan/index.md
Block/s
Update index Node(Server) S3 ŠD Day Plan.md
=> Update index Node(Server) S3 ŠD Day Plan.md

org-cyf/content/the-launch/_index.md, org-cyf/content/the-launch/prep/index.md, org-cyf/content/the-launch/sprints/1/day-plan/index.md, org-cyf/content/the-launch/sprints/1/prep/index.md, org-cyf/content/the-launch/sprints/2/day-plan/index.md, org-cyf/content/the-launch/sprints/2/prep/index.md, org-cyf/content/the-launch/sprints/3/day-plan/index.md, org-cyf/content/the-launch/sprints/3/prep/index.md, org-cyf/content/the-launch/sprints/4/day-plan/index.md, org-cyf/content/the-launch/sprints/4/prep/index.md
1. Restore the Launch links which got overwritten when we did the mega merge.  This is because these PRs were merged in during the changeover - bad timing. Fixes #586 
2. Also restored the old emoji as the staring girl alarmed me. 
3. Added short descriptions which can be edited
4. I'm not keen on these mega tabs. Can we perhaps use issues here? Or local blocks? The tabbed view as the only view seems hard to read. We can add specific issues to the prep view and use those tabs.
5. It seems like entry criteria should go in module/prep and exit criteria in module/success now we have those things
=> 586 Launch content isn't showing on Curriculum

common-theme/assets/styles/04-components/block.scss, common-theme/hugo.toml, common-theme/layouts/_default/day-plan.html, common-theme/layouts/_default/prep.html, common-theme/layouts/_default/single.html, common-theme/layouts/partials/block/pd.html, common-theme/layouts/partials/module-tabs.html, org-cyf/hugo.toml
Issue number: #597 
This is a button that links to the PD feedback form. The values are nil right now  - checking into why it isn't pulling from hugo.toml as expected 
UPDATE fixed - was not passing site context through
adds a button to link to pd form
=> add feedback button

org-cyf/hugo.toml
hugo.toml -- config
I'm turning on taxonomies. 
I'll go through and update common content with some categories. Here's my general concept:
categories= ['block', 'guide', 'term'] // the category of content
themes = ['state', 'side-effects'] // the learning theme
=> Feature: turn on taxonomies

common-theme/assets/scripts/mermaid-observer.js, common-theme/layouts/_default/_markup/render-codeblock-mermaid.html.html
1. prevent render
2. initialise on intersection
Fixes #411
An interaction between solo view and mermaid triggered a race mermaid reliably lost. My best guess is that the node the diagram was nested within was removed from the DOM before mermaid had completed its render. Mermaid consequently rendered the SVG with no dimensions, as it sizes itself automagically from its parent dimensions. It was still attaching data-processed="true" though, so it was a blob mess.
I went down a blind alley trying to find out how to re-render mermaid last time I looked at this. I concluded this was a fools' errand this evening and instead wrote an intersection observer that renders mermaid whenever the parent div hoves into view. It doesn't seem to hit performance. I concealed the unsightly FOUT with a small …
=> Mermaid fix: prevent loading until intersection

common-theme/layouts/_default/_markup/render-codeblock-mermaid.html.html, common-theme/layouts/_default/day-plan.html, common-theme/layouts/_default/list.html, common-theme/layouts/_default/module.html, common-theme/layouts/_default/prep.html, common-theme/layouts/_default/product.html, common-theme/layouts/_default/sprint.html, common-theme/layouts/_default/success.html, common-theme/layouts/partials/breadcrumbs.html, common-theme/layouts/partials/card.html, common-theme/layouts/partials/module-tabs.html, common-theme/layouts/partials/scripts.html, common-theme/layouts/shortcodes/wordlimit.html, org-cyf/hugo.toml
Fixes #603
On production, absURL was defaulting to / instead of the site root.
Seems like maybe it's because curriculum is a subdomain? In any case, I have added the url explicitly using baseURL
https://gohugo.io/methods/site/baseurl/
If this is the right fix I have some updates to the funding page, which I will open as a second tiny PR
https://deploy-preview-636--cyf-curriculum.netlify.app/guides/contributing/supporters/
#637
=> 603 Images are broken on https://curriculum.codeyourfuture.io/guides/contributing/supporters/

common-theme/layouts/404.html, org-cyf/content/404.md
I put a 404 page in. It just renders the site chrome. It would be nice to put a mini sitemap on this view however because we skip a level (skipping over /sprints/ to reduce the pointless clickery) it's a little more involved than the usual
```
{{ template "site-structure" (dict "dir" .Site.Sections) }}
{{ define "site-structure" }}
<ol>
{{ range .dir }}
{{ if (eq .BundleType "branch") }}
<li><a href="{{ .RelPermalink }}">{{ .Title }}</a>
{{ template "site-structure" (dict "dir" .Pages) }}
</li>
{{ else }}
<li><a href="{{ .RelPermalink }}">{{ .Title }}</a></li>
{{ end }}
{{ end }}
</ol>
{{ end }}
```
So I've skipped it for now in the interests of something being better than nothing.
404.html 
related to #649
content/404.md
=> feature: stub a 404 page

common-content/en/module/how-our-curriculum-works/importance-of-prep/index.md, common-content/en/module/how-our-curriculum-works/workshops/index.md
Fixes some typos/awkward phrases in the Self-Educate sprint of the How our curriculum works module.
Block/s
=> How our curriculum works/self-educate fixes

org-cyf/content/how-our-curriculum-works/sprints/self-educate/backlog/index.md
- Changes "week 1" to "self educate" for the issues in **self educate** section
=> filter for self educate issues

common-theme/layouts/_default/success.html
We used to collate all objectives blocks from readmes, PD, and local blocks on this page.
At some point without noticing we accidentally disabled objectives on local blocks.
This PR returns those objectives. I renamed the comparison to `local` from `local_module`. Clearly, this was once called local_module. It was renamed when we moved to using Hugo modules, I think?
Hat tip to Mitch for the fix!
layouts/success (SPRINTS)
Issue number: #679 
compare 
https://curriculum.codeyourfuture.io/html-css/sprints/2/success/
https://deploy-preview-688--cyf-curriculum.netlify.app/html-css/sprints/2/success/
=> Bugfix: return objectives to success page on sprint view

org-cyf/static/_redirects
add a redirect for the pr guide as per #694 hat tip to Esma!
=> 694 Create PR Guide link is broken

org-cyf/content/guides/getting-help/asking-questions/index.md
remove coupling to HTML-CSS module
I changed the link and wording to link to the asking questions workshop instead of a specific day, as this could move.
Guide | Asking Questions
=> Update Asking questions guide

org-cyf/content/js3/prep/index.md
This should be fixed a bit more robustly but for now let's add in the missing h2 #713  - opening this on github just as a markdown edit
JS3 | Prep |
=> add h2 to preamble

common-theme/layouts/_default/_markup/render-image.html, common-theme/layouts/partials/block/link.html, common-theme/layouts/partials/block/readme.html, common-theme/layouts/partials/strings/absolute-image-paths.html
1. _markup/render-image.html
revise render-image hook to do the following:
- update github links to github raw links (instead of jsdelivr)
- get all remote images and process as local instead of hotlinking
- incidentally, perform a mediatype check instead of file type check so we actually know it's a rasterisable image and not just some other file masquerading as same
2. strings/absolute-image-paths.html
then we made a short partial to run over decoded markdown blobs and regex with the path of the repo it's living in NOTE I DID NOT CONSTRUCT THIS REGEX please review my terrible regex 
3. blocks/readme.html
in the readme block, we added a second and final processing step to turn the relative links absolute. It has to be the last step so we can markdownify it inside the assignment. If we …
=> Feature: absolute image paths, get remote images

common-content/en/module/how-our-curriculum-works/day-plan/index.md, common-content/en/module/how-our-curriculum-works/importance-of-prep/index.md, common-content/en/module/how-our-curriculum-works/morning-orientation-block/index.md, common-content/en/module/how-our-curriculum-works/study-groups/index.md
Some of the **How our curriculum works** blocks currently point to other modules that won't exist in the new ITP. Just updating the instructions so the blocks are more reusable and less coupled to any particular module.
=> Decouple step instructions to specific modules

common-theme/layouts/partials/scripts.html
Add a custom js insertion point in scripts.html
This matches custom-theme and custom-images so you can add your own little scripts to your own theme. 
Make a script and add it to assets/custom-scripts to concat, minify, and insert
If you make a whole component please contribute it back to the common theme though.
=> Feature: custom js for individual sites

common-theme/layouts/partials/scripts.html
#727 from last night, we got a failure where custom-scripts had no matches. I have added custom-script folders to the other sites to alert them to the feature. I have then rewritten the concat to stop it failing on null. 
Issue number: #727 
check out this branch
rm/ re-add custom-script/index.js
witness its appearance and disappearance without failure
=> Bugfix: #727 followup, stop failure on null 

common-theme/layouts/_default/baseof.html
add a page class so when building other layouts it's easy to target specific pages without hassle
```scss
.p-home {
overrides here
}
```
=> add a page class so custom themes can target pages easily

common-theme/assets/scripts/solo-view.js, common-theme/assets/styles/03-elements/base.scss, common-theme/assets/styles/04-components/page-header.scss, common-theme/assets/styles/layout/footer.scss
Addresses #733 
1. Increase swipe to 96, or 2x tap target. Could go up to 144 edit, yes, 144
2. Swap 10vh height on toc to 12ch, so it will always show 3-5 lines
3. Kill the side scroll breaking out right
I might fiddle more with the toc later. 
Test on any prep view  eg https://deploy-preview-734--cyf-curriculum.netlify.app/js3/sprints/1/prep/
On a small mobile phone
=> Bugfix 733 : tweak mobile usability on solo view

content/employability/example-post/index-md.md, org-cyf-guides/static/admin/config.yml, org-cyf-guides/static/admin/index.html
CYF GUIDES > admin 
Ported the static CMS setup hanging out in a stale PR on CYF PD to see if we can give people some access to content on the guides impl. 
Just want to preview this to see what it's like really
https://deploy-preview-752--cyf-guides.netlify.app/admin/
https://app.netlify.com/sites/cyf-guides/overview
OK here's the deal.
I'm going to put this CMS on guides and just for employability for now.  I will likely also put it on common content BUT not if it means people start bypassing the review process. 
If we feel we want these on more sections, we can add them in per collection or per module. But we can't bypass the review process or we will get more low quality text creeping back in. So I reserve the right to remove these CMS-es if this happens. Stern face! (I do mean this - …
=> stub static cms PREVIEW

common-theme/layouts/overview/list.html, org-cyf/content/overview/_index.md
overview page - changed the get file lines to get page object instead
now the themes and blocks show up again
=> fix up overview to show again

common-theme/layouts/partials/map.html
Previously we were using the length of the _name_ as if it was the number of modules.
This introduces more explicit variable names for both.
=> Use correct variable for map module length

org-cyf-itp/content/overview/_index.md, org-cyf-itp/go.mod, org-cyf-itp/go.sum
updated name of Hugo module from org-cyf to org-cyf-itp
I need this to pull this course into a portal
Also the fixed overview page wants a nominated menu so I nominated one so the site would build -- Daniel loves to fail a build and I love to pass them :P
=> Bugfixes: update hugo module name

common-theme/layouts/_default/day-plan.html, common-theme/layouts/_default/success.html
Here are two small tests to make sure
1. the success page is compiling learning objectives, as this has broken silently before
2. the day plan has blocks on it, because without blocks it has no value
I have **not** added a third, more controversial test, on line 27 of prep.html
```
{{ else}}
{{ errorf "%s has no blocks in the front matter. Add blocks or remove the page" $.Page.RelPermalink }}
{{ end }}
```
As the sites would currently fail to build (13 blank views in the SDC). But pls consider this.
=> Two small tests for content

common-theme/assets/scripts/confetti-checkboxes.js, common-theme/layouts/partials/objectives/block.html
Persists confetti checkbox values in localStorage so trainees can track progress across sessions.
Issue number: #758 
=> Persisting confetti checkbox values in localStorage

common-content/en/module/induction/install-vscode/index.md, org-cyf-itp/content/data-groups/sprints/1/day-plan/index.md, org-cyf-itp/content/data-groups/sprints/2/day-plan/index.md, org-cyf-itp/content/data-groups/sprints/3/day-plan/index.md, org-cyf-itp/content/structuring-data/sprints/1/day-plan/index.md, org-cyf-itp/content/structuring-data/sprints/2/day-plan/index.md, org-cyf-itp/content/structuring-data/sprints/3/day-plan/index.md, org-cyf-itp/content/user-data/sprints/1/day-plan/index.md, org-cyf-itp/content/user-data/sprints/2/day-plan/index.md, org-cyf-itp/content/user-data/sprints/3/day-plan/index.md
Add morning orientation block to all ITP day plans
Minor change, making IDE = Integrated Development Environment
Issue number: #671 
Module
@CodeYourFuture/itp-syllabus-team
=> Add morning orientation block to all ITP day plans

common-theme/archetypes/day-plan.md, common-theme/assets/styles/03-elements/forms.scss, common-theme/layouts/_default/day-plan.html, common-theme/layouts/partials/register-attendance.html
Appears on every day plan unless you turn it off with noRegister. 
Netlify handles forms for you so I figured why not use that. I previously had set up a google form but longer term this probably has more advantages. For example it can detect what day it's on and what course it is in and send the data accordingly.
Later on we might want to put a user account option on curricula and connect to the Dashboard API, and in that case this could be evolved along with that. 
#612
=> Feature: register

common-content/deploy-netlify.sh, common-theme/deploy-netlify.sh, deploy-netlify.sh, org-cyf-guides/deploy-netlify.sh, org-cyf-itp/deploy-netlify.sh, org-cyf-piscine/deploy-netlify.sh, org-cyf-sdc/deploy-netlify.sh, org-cyf/deploy-netlify.sh, org-mcb/deploy-netlify.sh
We were previously not setting --baseURL which means that deploy previews have internal links to the prod deploys rather than the deploy previews.
Instead we introduce a script so that we can edit for all of the sites without needing to go change several site configs each time we want to make a change.
=> Add netlify deploy script

common-theme/archetypes/blocks/index.md, common-theme/assets/styles/04-components/page-header.scss, common-theme/layouts/_default/block-viewer.html, common-theme/layouts/partials/block/data.html, common-theme/layouts/partials/page-header.html, common-theme/layouts/partials/time.html, common-theme/layouts/shortcodes/blocklink.html, common-theme/layouts/shortcodes/columns.html, common-theme/layouts/shortcodes/logos.html, common-theme/layouts/shortcodes/note.html
Addresses #469 
I've written another documentation site. I threw away the first one because it didn't address the real questions users have.
To make this work I need to do three main bits of work:
1. Build a new view called block-viewer. I've put this in common-theme because people might want it for something else later. 
This view takes any blocks stored in a folder and displays them in a solo view format so you can page through them to take a quick look. 
Then the rest of the tweaks are stuff I encountered as I wrote the docs today, and are listed in the commit messages.
Once this PR is merged, move on to the actual docs site, which I will open soon common-docs #846 
Then the final piece is making some changes to common-content. Where previously we used headless=true to prevent render, …
=> Feature: block viewer  for docs 

common-docs/content/common-theme/blocks/prep/index.md, common-docs/content/common-theme/render-hooks/math.md, common-theme/layouts/_default/_markup/render-codeblock-math.html
documentation here: https://deploy-preview-862--cyf-common-docs.netlify.app/common-theme/render-hooks/math/
github has this so we should also. if someone writes math on github we want to display it as they expect
we may need it a bit in the sdc for a couple of things, but actually I want to draw logic and binary, which this doesn't do adequately
We should maybe put in CircuiTikz to draw logic, and something else to do the thing I might want to do with binary, or maybe we use a scrim.
https://www.mathjax.org/
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions
It's a render hook shortcode to add math with the string `math`
````
```math
````
=> Feature: a mathjax render hook

common-docs/hugo.toml, common-theme/hugo.toml, org-cyf-itd/hugo.toml, org-cyf-itp/hugo.toml, org-cyf-launch/hugo.toml, org-cyf-piscine/assets/custom-theme/states/dark.scss, org-cyf-piscine/assets/custom-theme/states/light.scss, org-cyf-piscine/hugo.toml, org-cyf-sdc/assets/custom-theme/states/dark.scss, org-cyf-sdc/assets/custom-theme/states/light.scss, org-cyf-sdc/hugo.toml, org-cyf-theme/assets/custom-theme/states/dark.scss, org-cyf-theme/assets/custom-theme/states/light.scss, org-cyf-theme/hugo.toml
#885 
this is sort of weirdly alluded to here
https://gohugo.io/hugo-modules/theme-components/
> Also note that a component that is part of a theme can have its own configuration file, e.g. hugo.toml. There are currently some restrictions to what a theme component can configure.
... Yeah
=> bugfix: markdown config cannot be inherited

common-docs/content/common-theme/render-hooks/note.md, common-theme/assets/styles/02-variables/colors.scss, common-theme/assets/styles/04-components/note.scss, common-theme/layouts/_default/_markup/render-blockquote.html, common-theme/layouts/shortcodes/note.html
create render hook
normalise our shortcode
dump old css
add missing colours
https://deploy-preview-887--cyf-common.netlify.app/common-theme/render-hooks/note/
#596
=> move to github notes

org-cyf-guides/content/_index.md, org-cyf-itp/hugo.toml, org-cyf-launch/content/demo day/_index.md, org-cyf-launch/content/sprints/1/_index.md, org-cyf-launch/content/sprints/2/_index.md, org-cyf-launch/content/sprints/3/_index.md, org-cyf-launch/content/sprints/4/_index.md, org-cyf-launch/go.mod, org-cyf-launch/go.sum, org-cyf-launch/hugo.toml, org-cyf-sdc/hugo.toml, org-cyf-theme/data/courses/itd.toml, org-cyf-theme/hugo.toml, org-cyf-tracks/hugo.toml, org-cyf/hugo.toml
and mount it where we want it
I've moved the guides to the main menu by adding it the syllabus menu
I've updated the link in the secondary menu from Guides to direct back to main curriculum
Except for on main curriculum where it goes to the main CYF site
=> promote guides to main menu

common-theme/assets/styles/02-variables/fonts.scss, common-theme/assets/styles/04-components/emoji.scss, common-theme/layouts/partials/card.html
adds an explicit fallback stack of emoji fonts
then assigns that to `c.emoji`
a gesture towards
Issue number #867
=> add a fallback font stack for emojis

common-theme/assets/styles/04-components/block.scss, common-theme/layouts/partials/block/link.html
the block link images were gone because the images were in flux and the location wasn't reliable. Now it's a fixed location
=> fix block link images

org-cyf/README.md
Updates documentation to correctly describe the creation of the `.env` file from `.env.example` in `org-cyf`
@SallyMcGrath , @jcholyhead
=> Correct readme.md to give correct required location of .env file

common-theme/layouts/partials/objectives/block.html
We already have a checkbox acting as a bullet point, we don't need an additional `-` which is an artifact of being a markdown bulleted list.
=> Trim leading - from objective bullet points

common-theme/layouts/partials/issues.html, org-cyf/tooling/netlify/functions/clone.ts, org-cyf/tooling/netlify/helpers/types.ts, org-cyf/tooling/netlify/helpers/util.ts
We don't currently have cloning functionality correctly set up on any of the other sites.
Rather than needing to set it up properly, and maintain copies of the netlify functions for each site, let's just use one copy of the netlify functions on curriculum. and redirect back to the appropriate site after cloning.
If we choose not to do this, we need to also set up a GitHub OAuth app per site, because a GitHub OAuth app is only allowed one callback domain.
It's possible we will need to futz with CORS for this, we'll see.
Once this works, I'll delete the other copies of the netlify function code.
=> Issue cloning always goes via curriculum.

org-cyf-itp/content/how-our-curriculum-works/sprints/self-educate/prep/index.md
The other two copies of this content include a dialogue block here, and the code review content links to it.
See also #922 for longer-term strategy about keeping these in sync.
=> Add missing dialogue block

common-theme/assets/scripts/solo-view.js
Previously if you had focused a child element (e.g. by expanding the learning objectives), the event would get handled multiple times.
Instead, stop propagation of the event.
Fixes #907
=> Don't double-navigate when pressing left/right

common-theme/assets/styles/04-components/block.scss
Fixes #906 
rm overflow hidden
this rule was handling a notes block and as we don't have this block we definitely don't need the acrobatics this rule would produce if we kept it
=> 906 Tooltip hovers can be overlapped / cropped

common-theme/assets/styles/03-elements/links.scss
there seem to be a few tiny scroll errors in here so I will fix them up too in a mo, but for now, this is the fix for this specific bug
the other error is on soloview, where the view is jumping around - might come back to that later
=> 919 Clicking in-page anchor links obscures the title of the item being clicked to

common-docs/hugo.toml, common-theme/hugo.toml, org-cyf-guides/hugo.toml, org-cyf-itd/hugo.toml, org-cyf-itp/hugo.toml, org-cyf-launch/hugo.toml, org-cyf-piscine/hugo.toml, org-cyf-sdc/hugo.toml, org-cyf/hugo.toml
this is a Hugo declared "unexpected behaviour" which I had fixed in itd when I saw it but failed to propagate
https://gohugo.io/methods/page/nextinsection/
apparently this page object is not heritable or not yet so I've copied it to all sites config FOR NOW
It seems like it's a mistake that this page object config is not heritable from common-theme, so I've added it in there and will check in a few months to see if we can remove these copypastas
It should be a common-theme setting, not a per site
=> 908 Backlog appears to be sorted before Prep in navigation

common-theme/assets/styles/04-components/tooltip.scss
position the tooltip from top instead of bottom to avoid the header
we don't really want to start trying to manipulate the z-index from inside a landmark so let's just move it down instead of up and and it will be mostly fine
=> 965 Tooltips can be hidden behind header

common-content/en/blocks/prep-dir-tests/index.md, common-content/en/blocks/prep-dir/index.md, common-content/en/module/how-our-curriculum-works/active-learning/index.md, common-content/en/module/js2/character-limit/index.md, common-content/en/module/js2/mean/index.md, common-content/en/module/js2/median/index.md, common-content/en/module/js2/multiple-params/index.md, common-content/en/module/js2/no-params/index.md, common-content/en/module/js2/one-pair/index.md, common-content/en/module/js2/ordered-data/index.md, common-content/en/module/js2/query-string/index.md, org-cyf-itp/content/data-groups/prep/index.md, org-cyf-itp/content/structuring-data/prep/index.md
Add a bunch of cues throughout to actually code along
Explicitly direct trainees to create a folder in their coursework dir to codealong in
Add motivations for active learning eg The Research
Yep
Fixes #855
Data groups | Prep 
Data groups | Sprint 1 | Prep
Data groups | Sprint 2 | Prep
Data groups | Sprint 3 | Prep
Structuring and testing data | Prep
=> 855 Data Groups / Sprint 1 - Explicitly ask trainees to code-along with prep?

common-theme/layouts/_default/_markup/render-link.html
It seems like sometimes Hugo is recognising a link and sending it through its markdown render loop into this render hook, but this render hook uses Go parse https://pkg.go.dev/net/url#Parse and can't handle spaces or quotes. 
So I trimmed 'em.
I think I probably want to log bad links, but not fail all builds when one link somewhere is bad -- that seems like a terrible development experience! Anyone who wants to sort that out please do.
Fixes #990
=> Bugfix 990: bad link

common-theme/assets/styles/04-components/page-footer.scss, common-theme/layouts/_default/sprint.html
Adds a tiny section nav to sprint views
Because it's annoying me editing the url all the time to sprint around
yep, no ticket, just would like it and it seemed simple
Go to http://localhost:1313/user-data/sprints/3/ for example and see the same section nav appear as is already on other pages
I added a return to the module parent at the end but you could rm this and have it empty if you prefer -- get your hands on it
=> add nav for sprints

common-content/en/blocks/workshop/index.md
let's just try  knocking down the text instead for now
We can revisit this when we are not rushing to launch
=> we probably don't want more boxes in boxes

common-content/en/module/html-css/what-are-forms/index.md, common-content/en/module/induction/checkout-a-commit/index.md, common-content/en/module/induction/cyf-blog/index.md, common-content/en/module/induction/development-process/index.md, common-content/en/module/induction/previous-versions/index.md, common-content/en/module/induction/viewing-files/index.md, common-content/en/module/induction/wrapping-up/index.md, common-content/en/module/js1/assembly/index.md, common-content/en/module/js1/clocks/index.md, common-content/en/module/js1/strategy/index.md, common-content/en/module/js2/plan/index.md, common-theme/layouts/_default/overview.html, org-cyf-itp/content/structuring-data/sprints/1/_index.md, org-cyf-itp/content/structuring-data/sprints/2/_index.md, org-cyf-itp/content/user-data/sprints/1/_index.md, org-cyf-itp/content/user-data/sprints/2/_index.md, org-cyf-itp/content/user-data/sprints/2/prep/index.md, org-cyf-itp/content/user-data/sprints/3/_index.md, org-cyf-itp/content/user-data/sprints/3/prep/index.md
* Update themes to reflect actual content
* Make some titles more clear
* Hide a few "just process, not content" prep items from overview
* Allow specifying titles in the blocks list (e.g. for external blocks like YouTube videos), rather than requiring blocks specify them in their own frontmatter.
=> Tweaks to ITP overview

org-cyf-itp/content/user-data/prep/index.md
We've now updated the "Set up Planner" to cover the full step-by-step process and included screenshots. Moving this after the videos, as participants can first watch the videos before attempting to set up the planner themselves.
Issue number: #1018 
@CodeYourFuture/itp-syllabus-team
=> Moving the setup planner section after the planner-related videos

common-theme/static/404.html
Hugo will correctly replace this with the actual rendered 404 page. But if this file doesn't already exist with the correct permissions, hugo will for some reason which we can't debug create a placeholder file with permissions 0444 instead of 0644, and then won't be able to overwrite it with the correctly rendered file.
Fixes #992 somehow, even if we don't really know how.
=> Create a placeholder 404 file with the correct permissions

common-theme/layouts/partials/foot.html
Added button style for correct cursor pointing when hovering the toggle button of the dark theme
Issue number: #888 
=> feat: add pointer to toggle mode button

common-theme/layouts/_default/success.html
Also, add missing LOs so this check doesn't fail.
=> Error if a module success page is missing learning objectives

common-content/en/module/js2/update/index.md, common-theme/assets/scripts/word-limit.js
textContent is a better default as it doesn't force reflows.
We can introduce innerText as/when it's needed.
- `common-content/en/module/js2/update/index.md`
- `common-theme/assets/scripts/word-limit.js`
=> Use textContent not innerText

common-theme/layouts/partials/issues.html
I always forget this API won't let you do it up top - have to do it after pulling them through, hence the need for Daniel's cache
I've filtered out PRs so they won't show up even if a trainee labels their PR with a sprint label, which I guess sometimes someone might do!
See https://codeyourfuture.slack.com/archives/C076K3V76CA/p1729175848173849 for more context
with filter
without
=> Bugfix: trainee PR showing up in backlog : filter out PRs

org-cyf-itp/netlify.toml
Currently trying to fetch them fails due to CORS.
=> Set CORS headers for dummy APIs

org-cyf-itd/content/blocks/step-0/acceptance/index.md, org-cyf-itd/content/blocks/step-0/instructions/index.md, org-cyf-itd/content/blocks/step-0/submission/index.md, org-cyf-itd/content/steps/five/index.md, org-cyf-itd/content/steps/four/index.md, org-cyf-itd/content/steps/one/index.md, org-cyf-itd/content/steps/six/index.md, org-cyf-itd/content/steps/three/index.md, org-cyf-itd/content/steps/two/index.md, org-cyf-itd/content/steps/zero/index.md
This adds ITD step zero which previously only existed in the dashboard. In addition, it makes some edits to step zero to conform with the requirements of #1057  
No
No
Issue number: #1057 #958 
No
- [ x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
@kfklein15
=> Add step 0

common-content/en/module/js1/interpreting-errors/index.md, common-theme/layouts/shortcodes/note.html
I think this was accidentally changed in
7287ff7c75f944eb4a79f871e40425ec3d4ba3d7?
This isn't a pure revert - it sets up a fallback chain of title > type > Note rather than just title > Note
Trivially, sets up some example titles (as requested in #1033).
Yes - changes the note shortcode.
=> note shortcode: Use title as title when specified

common-theme/assets/styles/04-components/tooltip.scss
Tab titles are already at 2.
I'm sorry Sally.
Fixes #1106
=> Bring tooltips further forward

common-theme/layouts/partials/breadcrumbs.html, org-cyf-itd/content/steps/_index.md
Part 3 of #1105 
Other parts #1130  #1131 
1. suppress step index view as it's just the same info as the home page
2. skip this inaccessible page in breadcrumbs
=> 1105 suppress step view

common-docs/hugo.toml, common-theme/assets/styles/02-variables/fonts.scss, org-cyf-theme/hugo.toml
Add Noto emoji font and switch up the fallbacks. Will test on an ancient Windows machine tomoz
Fixes #867
=> 867 Use only quotidian emojis in emoji field

common-theme/layouts/partials/block/data.html, common-theme/layouts/partials/strings/readme-paths.html, org-cyf-itp/content/user-data/sprints/1/day-plan/index.md
As per #1001, adds a new strings util to transform github readme api paths. 
I've changed the format of a link on ITP> UFD > 1 > Dayplan  to show this. This is how it worked before we broke it at some point, but I've done it in a more robust way now - I've hived it off into a separate, well commented partial that the data partial can call. 
It is probably desirable to do this with most of the string transforms over time.
Fixes #1001 readme regex
UFD | 1 | Dayplan | Workshop
=> 1001 Bug: readme links not being cleaned

common-content/en/module/js2/browser/index.md, common-content/en/module/js2/calculating/index.md, common-content/en/module/js2/character-limit/index.md, common-content/en/module/js2/check-progress/index.md, common-content/en/module/js2/dom/index.md, common-content/en/module/js2/events/index.md, common-content/en/module/js2/plan/index.md, common-content/en/module/js2/querying/index.md, common-content/en/module/js2/reacting/index.md, common-content/en/module/js2/refactor/index.md, common-content/en/module/js2/update/index.md, org-cyf-itp/content/data-groups/sprints/3/prep/index.md
Fixes https://github.com/CodeYourFuture/curriculum/issues/332
This way, we:
* Fully handle accessing and setting DOM element properties in one chunk, then introduce events, rather than muddling the two together.
* Identify that there are two common actions to do, and talk through identifying and addressing this.
* Pull out the "what is the character limit" to be defined by the HTML attribute, rather than duplicated in the script.
* Practice breaking down the "remaining characters" problem into sub-problems.
* Generally solve things more incrementally.
* Explicitly call out "do a clean-up refactoring" at the end.
Also some misc copy edits.
Yes - changes, reorders, and adds blocks to much of JS2.
Data Groups Sprint 3
=> Rework DOM to better separate elements from events

common-content/en/module/induction/accounts/index.md
We want our trainees to set up images on their accounts - make this explicit and add image selection guidance. (While still suggesting alternatives for people who can't include images of themselves).
- `common-content/en/module/induction/accounts/index.md`
=> Add guidance about profile pictures

common-theme/layouts/partials/strings/readme-paths.html
This adds in a catch for the case where it's the root of the repo readme but /tree/main is on the path.
This is fine but the real question is why isn't the error caught in readme.html
=> add regex to catch case

common-theme/layouts/partials/block/block.html, common-theme/layouts/partials/block/readme.html
GetRemote returns nil not an error in this case
Also, fail the build on unrecognised block types.
=> Error if a README couldn't be found

org-cyf/content/_index.md
adds link to 2024/25 Schedule until we have a calendar view
it's on the home page of the curriculum portal
=> add planner

common-theme/layouts/_default/day-plan.html, common-theme/layouts/_default/prep.html, common-theme/layouts/_default/single.html, common-theme/layouts/partials/block/local.html, common-theme/layouts/partials/block/pd.html, common-theme/layouts/partials/block/readme.html, common-theme/layouts/partials/foot.html, common-theme/layouts/partials/header.html, common-theme/layouts/partials/issues.html, common-theme/layouts/partials/module-tabs.html, common-theme/layouts/shortcodes/logos.html, common-theme/layouts/shortcodes/our-name.html, org-cyf/layouts/partials/map.html
Use `site` not `$.Site`
These are equivalent when they happen to be called in a context that has `.Site`, but `$.Site` breaks if the current context doesn't have a `.Site`.
Because `site` _always_ works, and when they both work they're exactly equivalent, prefer to use it. This makes future refactorings less brittle.
=> Use site not $.Site

common-theme/layouts/shortcodes/objectives.html, common-theme/layouts/shortcodes/tasks.html
this is temporary - we probably want to not just use codefencing and use commented out hugo shortcodes so the task lists still work on github. So here are the entry files for those shortcodes so they can start being used. 
However we actually don't want this sort of horrible ball of code and it makes sense to rationalise  all these various ways of getting objectives in order to make the success page cleaner.  
But that's a task for a clearer head than I currently have, so here, a quick fix so annotation can proceed without breaking the build
Issue number: #issue-number Partial towards #950
=> TEMP files for objective and task shortcodes

org-cyf-itp/content/data-groups/sprints/1/day-plan/index.md, org-cyf-itp/content/data-groups/sprints/2/day-plan/index.md, org-cyf-itp/content/data-groups/sprints/3/day-plan/index.md
=> Adds workshop recommendations to module 3

org-cyf-guides/content/presenting/_index.md, org-cyf-guides/content/presenting/demoing/index.md
Add guide on presenting, and specifically demoing
We rely on demos in a bunch of places (weekly demos, Piscine demos, Launch demos, CYF+ demos). This guide attempts to prevent some of the really common issues we see in these demos.
We can expand this over time.
I've specifically carved out a "Presenting" guide with "Demos" as a sub-section, because a lot of this advice applies to all presentations. We can add more presentation types as sub-sections as needed.
See deploy preview: https://deploy-preview-1197--cyf-programming.netlify.app/guides/presenting/
Adding a guide
=> Add guide on presenting, and specifically demoing

common-content/en/module/js1/install-node/index.md
- Issue was reported here: https://codeyourfuture.slack.com/archives/C076K3V76CA/p1730546048389919
- Adjusts the Node Setup instructions to work seamlessly for Mac OS
- Instructions tested on a fresh install Mac OS (virtual machine)
```sh
baz@bazs-Virtual-Machine ~ % xcode-select --install
xcode-select: note: install requested for command line developer tools
baz@bazs-Virtual-Machine ~ % touch ~/.zshrc
baz@bazs-Virtual-Machine ~ % curl -0- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | 
...
=> Appending nvm source string to /Users/baz/.zshrc
=> Appending bash_completion source string to /Users/baz/.zshrc
...
baz@bazs-Virtual-Machine ~ % source ~/.zshrc
baz@bazs-Virtual-Machine ~ % nvm install --lts
...
baz@bazs-Virtual-Machine ~ % node -v 
v22.11.0 …
```
=> itp: js1: install node: adjust nvm instructions for mac os

org-cyf-itd/content/blocks/step-3/instructions/index.md
Add an item in step 3 (under "What to do") to direct the participant to study "What to do and what to avoid when taking Scrimba Course" (aka the "Scrimba FAQ").
@SallyMcGrath
=> Add in step 3 a link to the "Scrimba FAQ"

common-content/en/module/the-launch/presentation/index.md
Remove old presentation from Launch and link users to our guide
Module
=> Update Launch Module presentation.md

common-content/en/energisers/popcorn-screen-share/index.md, common-content/en/energisers/popcorn/index.md, common-content/en/energisers/slack-libs/index.md, common-content/en/energisers/word-chain/index.md
These were hanging around from before my break. Some early course energisers, suitable for Intro Module.
Yep, all energisers, none assigned to a day plan yet  - this is just supporting material #1168 
@CarolineFrank35 FYI  - I knocked these up before my break and just found them hanging out in this branch.
=> 1168 in support of Assign an energiser to the day plans in ITP

common-content/en/module/js2/key-values/index.md
it amends the sentence that was written incorrectly. 
it amends the sentence: "there are **3** properties"  to  "there are **4** properties" .
Path to the file: curriculum/common-content/en/module/js2/key-values/index.md
Yes
=> Fix typo in the number of properties

common-theme/assets/scripts/time-stamper.js, common-theme/hugo.toml, common-theme/layouts/_default/day-plan.html
Sets the start time on the time stamper component.
Updates params on the day plan default layout. 
Issue number: #1002
=> Set start time on time stamper component

common-content/en/module/piscine/programming-prereqs/index.md
See discussion from https://codeyourfuture.slack.com/archives/C012UUW69S8/p1729604686501789?thread_ts=1729514033.295269&cid=C012UUW69S8
We will re-add error handling when we've re-added this to ITP.
The Jest updates are reflecting what we actually teach in ITP - the other things aren't super necessary they're Just More APIs.
Switch isn't needed and can be picked up as needed through Google.
Yes, but this is maybe actually super CYF specific and maybe all the Piscine stuff should get moved into the Piscine module.
=> Remove obsolete prereqs from Piscine

common-content/en/module/js1/anonymous-functions/index.md, common-content/en/module/js1/arrow-functions/index.md, common-content/en/module/js1/generalise/index.md, common-content/en/module/js1/outliers/index.md, common-content/en/module/js2/mean/index.md, common-content/en/module/js2/median/index.md, org-cyf-guides/content/testing/intro/index.md
Replace `toBe` with `toEqual`
These were meant to be changed before, but apparently I missed a few.
toEqual is a good default, and toBe is something that generally only makes sense in more limited use-cases.
Yes, but only trivially
=> Replace toBe with toEqual

org-cyf/layouts/partials/map-menu.html
grab new moved context so the home page is not empty
https://curriculum.codeyourfuture.io/
=> HOTFIX HOME PAGE IS EMPTY 

common-theme/layouts/partials/issues.html
Sorts issues on the backlog view by title.
This is a tiny upgrade so we can merge the project. However, I've also converted this whole view to graphql (not appearing in this PR)  which means it can plug in to the blocks loop instead of doing its own separate thing. 
https://gist.github.com/SallyMcGrath/88626b3c219cb74fe844aedd7f3cd586
At some later less time pressured date I'll open that PR. For now let's sort those issues in a rudimentary fashion!
Towards #1204 #1189
=> sort issues by title

common-docs/content/common-theme/shortcodes/multiple-choice.md, common-theme/layouts/shortcodes/multiple-choice.html
Allow specifying a custom delimiter for multiple choice quizzes
I'm writing quizzes on shell pipelines, and I need to include |s in my answers.
=> Allow specifying a custom delimiter for multiple choice quizzes

common-theme/assets/scripts/time-stamper.js
On the day plan, if you nest blocks as options, the time stamp accumulates them and the times go wrong.
I've excluded nested blocks from the timestamper.
=> fix that annoying time bug on day plan

common-content/en/module/onboarding/goals/index.md, org-cyf-itp/content/onboarding/success/index.md
We do not require that everyone participating in ITP is eligible to enroll as a trainee. But we do require that to have completed the Onboarding module you must have applied.
Frame success as _applying_ to enroll as a trainee, rather than framing success as contingent on being positively enrolled as a trainee.
We want everyone to apply. It's ok if not everyone is eligible. But we're trying to anchor people to a path of applying.
=> Soften requirements to from "enroll to be a trainee" to "apply to be a trainee"

common-theme/layouts/_default/overview.html, org-cyf-itp/content/overview/_index.md, org-cyf-itp/content/welcome/prep/index.md
@SallyMcGrath it looks like in https://github.com/CodeYourFuture/curriculum/pull/1241 you removed all of the modules from the `programming` menu... Was this intentional? The overview page is currently being driven by that - can we either change what menu the overview page is driven from, or re-add the `programming` menu?
=> Re-fill overview page, and error if it's empty

tooling/common-config/deploy-netlify.sh
$DEPLOY_PRIME_URL appears to point at a .netlify.app version of the site, rather than the URL it's actually getting deployed as.
This manifests as a bunch of CORS errors like:
> Access to manifest at 'https://main--cyf-programming.netlify.app/manifest.json' from origin 'https://programming.codeyourfuture.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
=> Use $URL not $DEPLOY_PRIME_URL

common-docs/package.json, common-theme/package.json, org-cyf-itd/package.json, org-cyf-itp/package.json, org-cyf-piscine/package.json, org-cyf-sdc/package.json, org-cyf-tracks/package.json
https://gohugo.io/troubleshooting/audit/
This exists now, so maybe we should use it. 
I've stored it in package.json but may wish to extend this or build it in elsewhere like as an action on PR.  Have at it.
Would catch things like #1271
=> add an audit option

common-content/en/blocks/standup/index.md, common-content/en/energisers/introduce-yourself/index.md, common-content/en/energisers/time-traveller/index.md, common-content/en/energisers/word-chain/index.md, org-cyf-itp/content/structuring-data/sprints/1/day-plan/index.md, org-cyf-itp/content/structuring-data/sprints/2/day-plan/index.md, org-cyf-itp/content/structuring-data/sprints/3/day-plan/index.md
- slowly fade onboarding "blockers" and "wrap"  into standups and retros
- assign workshops they have context for
- add structured activities to introduce coursework tasks
Fixes #1182
Fixes #1168 
- standup block
- tweaked some energisers
STAD | 123 | Day Plans
=> Content: STAD day plans update

org-cyf-tracks/hugo.toml
adds goldmark config to tracks  because this cannot be inherited from theme 
without configuring goldmark anything which does complex mixes of md and html goes wrong. You can tell it's goldmark, or a markdown rendering problem mixing in HTML, because in the rendered view it says ``
Fixes #1211 
Tracks | hugo.toml
=> 1211 details tags don't show up inside note

org-cyf-how-this-works/content/sprints/self-coordinate/backlog/index.md, org-cyf-how-this-works/content/sprints/self-educate/backlog/index.md, org-cyf-how-this-works/content/sprints/self-evaluate/backlog/index.md
Some of these emojis exist on github but not Hugo so the perfect match filter fails and the backlog is empty. I have removed the emojis for safety in this case.
=> rm emojis from label filter on how this works

common-docs/content/common-theme/pages/day-plan.md
The build is currently failing because we have some complicated PRs in curriculum which include unknown shortcodes in their descriptions.
Ideally this wouldn't cause problems for the site, but it does, so... Let's switch to a repo which is less likely to trigger this problem.
=> Switch sample day-plan PRs to less interesting repo

common-content/en/module/js2/variable-keys/index.md
this one was missed somehow so is breaking data-groups/sprints/2/prep/#access-with-variables
Have searched and found no more
#1268
=> Fix: cleanup after tabs work

org-cyf-piscine/content/module/piscine/application/index.md, org-cyf-piscine/go.mod
Make application requirements, and what happens if you fail the test, more clear.
Piscine blocks.
=> Clarify Piscine application process

org-cyf-sdc/content/blocks/get-how-computers-really-work/index.md
Matthew Justice has very kindly donated a PDF of the book to CYF for use by our trainees, which means we have a much better answer for "how do you get this book if you can't afford it?" now!
This block overrides the common-content version of this block, because it's a CYF-specific donation.
=> Clarify access to How Computers Really Work

org-cyf-piscine/content/sprints/1/backlog/index.md, org-cyf-piscine/content/sprints/2/backlog/index.md, org-cyf-piscine/content/sprints/3/backlog/index.md
Fixes incorrect repo names used in the Backlog for the Piscine - it seems we renamed the coursework repo from `Module-Piscine` to `The-Piscine` at some point.
While it continues to work (because Github maintains redirects for renamed modules), it seems to make the most sense to fix the names to be correct.
Issue number: N/A, just noticed while reviewing the Piscine content
Module
=> Fix incorrect repo names for Piscine

common-theme/layouts/_default/day-plan.html, common-theme/layouts/partials/register-attendance.html, org-cyf-itp/content/welcome/_index.md, org-cyf-itp/hugo.toml, org-cyf-itp/tooling/netlify/functions/submission-created.js, org-cyf-piscine/content/sprints/_index.md, org-cyf-theme/data/courses/cyf-piscine.toml, org-cyf-theme/data/courses/itd.toml, org-cyf-theme/data/courses/itp.toml, org-cyf-theme/data/courses/launch.toml, org-cyf-theme/data/courses/piscine.toml, org-cyf-theme/data/courses/sdc.toml, org-cyf-theme/data/courses/systems.toml
pulls location data from course data files stored in org-cyf-theme
removes family name because it's too many fields
courses data files
Fixes #1113 
Register includes locations
=> 1113 Register must include location and made available to local leaders

common-content/en/module/piscine/kickoff/index.md, common-content/en/module/piscine/practice-break-down/index.md, org-cyf-piscine/content/sprints/1/day-plan/index.md, org-cyf-piscine/content/sprints/2/day-plan/index.md
* Note that groups may be 2 people.
* Add temporary block for talking through breaking down requirements. We hope to remove this in the future, but we would like our day plans to be accurate for the course we're delivering.
* Move team-selection to happen before morning break.
=> ~Final tweaks to Piscine

common-content/en/module/piscine/practice-break-down/index.md
Extends the temporary workshop added in https://github.com/CodeYourFuture/curriculum/pull/1325 with exercises to break down a couple of requirements from the first Piscine project (spaced repetition tracker).
This is something of a strawman - please feel free to tear it apart!
I've chosen not to explicitly write out the tickets that I was thinking of, but they were something like:
- Add form submit button
- On submit, store some hard-coded data (user 1, today's date, any topic)
- Read the data (hard coded to user 1 for now) from storage
- Display the first date from the data
I also chose not to include exercises on writing up tickets - I wasn't sure how to frame that as an exercise and I wanted to get something in soon. But will try to think about that this week.
Issue number: N/A
Module …
=> Extend temp Piscine workshop with exercises to breaking down project requirements

org-cyf/content/_index.md
Previously we were linking to the sheet the public view is a proxy for, which means it didn't get updated when we updated the proxy.
Also, remove 2024 from the link text, we're in 2025 now.
=> Link to the public view of the calendar

common-theme/assets/styles/04-components/objectives.scss
This fixes a display bug in Safari. Safari does not implement ::marker completely.
https://bugs.webkit.org/show_bug.cgi?id=204163
So I removed ::marker and used ::before. 
I also removed the font size as the new emoji is the right size on OSX.
@illicitonion
=> switch from marker to before

org-cyf-sdc/content/logic/sprints/1/day-plan/index.md
* Move rats to morning
* Give more time for games - it's games week!
* Give more time for logic teaching
* Add in a regular demos slot - demos _every_ week!
* Switch back to retro - we're doing retros rather than wraps for most of SDC.
=> Tweak logic day-plan timings

common-content/en/blocks/games/index.md, common-content/en/module/tools/computer-quiz/index.md, org-cyf-sdc/content/tools/sprints/1/prep/index.md
=> Added quiz learning objectives for Chapters 1 & 2

common-theme/layouts/shortcodes/tooltip.html
so it doesn't break in notes, as per https://github.com/CodeYourFuture/curriculum/pull/1268
=> Fix: put tooltip html in one line

common-docs/content/common-theme/shortcodes/label-items.md
cause I'm using it
.../common-theme/shortcodes/label-items => https://deploy-preview-1408--cyf-common.netlify.app/common-theme/shortcodes/label-items/
documents #1316 #1338
=> document label items

common-theme/assets/styles/04-components/toc.scss
I removed the text-transform: lowercase; rule from the Table of Contents (TOC) because it was making the text all lowercase. This change allows the TOC text to stay as it is.
=> Removed lowercase rule from TOC

common-content/en/module/databases/databases-with-sheets/index.md
This PR fixes a typo in the Sprint 2 prep page. The table diagram had "Column 1" listed twice. I corrected the second "Column 1" to "Column 2" to reflect the intended structure.
Issue number: N/A
onboarding | 2 | prep | text
@CodeYourFuture/dashboard-developers
=> Fix typo in Sprint 2 prep table (duplicate "Column 1")

org-cyf-itp/content/structuring-data/success/index.md
The Success criteria for module "Structuring and Testing Data".
1. Include Sprint 1 and Sprint 2 Coursework Exercises (before the Coursework Exercises only link to Sprint 3's Coursework)
2. State clearly what to submit as evidence when they finished the "Intro to Python" section of the CIP course.
ITP | Module Structuring and Testing Data | Content | Success 
`org-cyf-itp/content/structuring-data/success`
@CodeYourFuture/curriculum
=> Update Success Criteria for ITP Structuring-Data module

README.md, org-cyf-guides/README.md
This PR changes a block on the 2 README pages :
- Added guides link `https://guides.codeyourfuture.io/` in the Examples section
- Fixed broken link `https://guides.codeyourfuture.io/` with working link `https://curriculum.codeyourfuture.io/guides/` in `org-cyf-guides` folder
Fixes #1319
Issue number: #1319 
Block Type
@mbadrawy1 @chinar-amrutkar
=> Fix broken guides links in 2 README files sections

common-content/en/module/tools/process-spelunking/index.md
The content of the tutorial on LSOF
Module | Sprint | Page Type
Tools | Sprint 3 | Index
spotted by @OracPrime
=> fix typo in LSOF

common-theme/layouts/partials/card.html, org-cyf-itp/content/piscine/index.md, org-cyf-itp/hugo.toml
Currently the mounting means that site-specific overrides (e.g. the application form) don't get overridden.
We really just want a link here.
=> ITP: Link to Piscine instead of mounting it

org-cyf/content/_index.md, tooling/common-config/netlify.toml
Rather than needing to know a Google Doc link, this allows going to https://curriculum.codeyourfuture.io/calendar
=> Add /calendar redirect

org-cyf-guides/content/contributing/minutes/index.md
=> Added minutes from meeting on 2025-07-29

common-theme/assets/styles/04-components/block.scss, common-theme/layouts/partials/block/block.html, common-theme/layouts/partials/block/codewars-workshop.html, common-theme/layouts/partials/block/data.html, org-cyf-itp/content/structuring-data/sprints/1/day-plan/index.md, org-cyf-itp/content/structuring-data/sprints/2/day-plan/index.md, org-cyf-itp/content/structuring-data/sprints/3/day-plan/index.md, org-cyf-itp/go.mod
Tony has been developing these, here's a proof of concept for embedding them into the curriculum.
Long-term we may want a custom generator that does closer integration into the static site generator, but for now iframing things in works fine.
=> Add Codewars workshops to Structuring and Testing Data

common-theme/layouts/partials/multiple-choice.html
Different quizzes in the same page apparently share the same ID space for labels, even though they're in separate shadow roots.
Fortunately, the `<input>` tags are nested inside the `<label>` tags, so the `for` attribute isn't necessary, they implicitly bind to their contained tag.
So removing the `for` attribute here preserves the desired behaviour, while removing the confusion of which element is being targeted.
Fixes #1410
=> Fix multiple choice click capturing

org-cyf-itp/content/welcome/backlog/index.md
We try to use the Welcome sprint as an example of how all sprints work.
But not having a backlog makes it unusual, and means it's a bad example.
Add a backlog with a couple of useful tasks to do before the welcome day.
=> Add backlog to Welcome sprint

common-content/en/module/tools/nodejs/index.md
Duplicate word in prep text
Issue number: no issue number, this is technically a typo
SDC | sprint 3 | module index page (index.md) | N/A
=> fix double word in sdc tools sprint3 prep

common-theme/assets/styles/04-components/course-overview.scss, org-cyf-theme/data/courses/itp.toml, org-cyf-theme/data/courses/piscine.toml, org-cyf-theme/data/courses/sdc.toml, org-cyf/content/_index.md, org-cyf/content/overview/index.md, org-cyf/layouts/_default/overview.html
I perpetually re-create this display in slide decks - let's centralise the content somewhere we can link to.
Right now it's not _beautiful_, but it exists. We can make it prettier.
=> Add overview page showing the software pathway

common-theme/layouts/_default/backlog.html
These are noisy and people find them confusing. They still exist on the issues, but we put them less in people's faces.
=> Remove labels from backlog page

org-cyf-itp/content/structuring-data/success/index.md
Update the module Success criteria 
- Remove "Evidence you have completed “[Intro to Python]"
- Add "Evidence you have completed at least 60% of the Codewars katas for this module"
I have also updated the corresponding issues in the Module-Structuring-and-Testing-Data repo 
- https://github.com/CodeYourFuture/Module-Structuring-and-Testing-Data/issues/25
- https://github.com/CodeYourFuture/Module-Structuring-and-Testing-Data/issues/26
- https://github.com/CodeYourFuture/Module-Structuring-and-Testing-Data/issues/27
I didn't touch the [CIP: Intro to Python issue](https://github.com/CodeYourFuture/Module-Structuring-and-Testing-Data/issues/21) because closing it would leave a "missing number" in Sprint 1 backlogs.
Modified the Success page of the Module Structuring and Data. …
=> Replace CIP by Codewars in Module Success

tooling/common-config/netlify.toml
As with /calendar, this is a handy link to not need to dig out a Google Docs link when referencing.
=> Add link to other schools
