CodeYourFuture/curriculum

.gitignore
assets/scripts/random-emoji.js

Removes an unnecessary log and gitignores a Hugo build lockfile. Noticed while experimenting with the codebase.

Clean up a couple of things

---

content/databases/blocks/block1/index.md
content/databases/blocks/block2/index.md
content/databases/blocks/block3/index.md
content/final-projects/blocks/block1/index.md
content/final-projects/blocks/block2/index.md
content/final-projects/blocks/block3/index.md
content/html-css/blocks/block1/index.md
content/html-css/blocks/block2/index.md
content/html-css/blocks/block3/index.md
content/js1/blocks/block1/index.md
content/js1/blocks/block2/index.md
content/js1/blocks/block3/index.md
content/js2/blocks/block1/index.md
content/js2/blocks/block2/index.md
content/js2/blocks/block3/index.md
content/js3/blocks/block1/index.md
content/js3/blocks/block2/index.md
content/js3/blocks/block3/index.md
content/node/blocks/block1/index.md
content/node/blocks/block2/index.md
content/node/blocks/block3/index.md
content/react/blocks/block1/index.md
content/react/blocks/block2/index.md
content/react/blocks/block3/index.md
create_module.sh

The default time was set as an hour eg 0.3 for 20 minutes
It should have been set as minutes eg 20
I have corrected this in the module script
And updated the example blocks generated from this script
None of these blocks will survive content population but it's a bad example, so I have rectified

Time default should be set in minutes

---

assets/styles/02-variables/colors.scss
assets/styles/02-variables/shadows.scss
assets/styles/03-elements/headings.scss
assets/styles/04-components/note.scss
layouts/shortcodes/note.html

I found them a bit obnoxious with loads on a page
I knocked the font size down, removed the block background on the heading, and added a slimmer shadow (1/3)
Also added some extra icons and alts for tips and glossary

revise note styles

---

layouts/shortcodes/iframe.html

We probably want something more like this? We will mainly use this for cyf blocks I guess?
Test on the fundamentals content I just PRd --- sprint 1 day plan

tweak iframe settings

---

layouts/shortcodes/youtube.html

just takes a link as inner, no arguments
This is a copypasta of the youtube partial, with the extraneous block stuff removed as it's already in a block

create a youtube shortcode

---

assets/scripts/tab-panels.js
assets/styles/04-components/tabs.scss
layouts/shortcodes/tab.html
layouts/shortcodes/tabs.html

For including stuff like facilitator notes or answers
Written as a web component - maybe we want password locking in the future.

tabs component

---

assets/scripts/tab-panels.js
assets/styles/04-components/tabs.scss
layouts/_default/module.html
layouts/partials/module-tabs.html

feedback on fundamentals was that the prep page was too long and the goals should go elsewhere -- I've made this module tabs view to add in this kind of content. I will also set a short piece of coursework to find, read, and answer some basic questions on this content.

module tabs variation

---

layouts/shortcodes/tabs.html

Follow up to #15, I was looking to understand the code and ended up tidying up the indentation. I think I also fixed a bug too? I removed a stray `<p>` that shouldn't have been in there.
Sorry for the nitpicky PR!
@SallyMcGrath

Clean up indentation of tabs shortcode

---

content/fundamentals/prep/index.md

Week(s): Prep overall
Adding the link of the agreements reading/signature that must be done before Fundamentals. 
I added it here, but if needed, can move it to Week 1.

Update index adding Agreement to overall prep for Fundamentals.md

---

content/fundamentals/sprints/1/day-plan/index.md

Week(s): 1
This change is to add the 2 PD blocks to the main Syllabus
@SallyMcGrath

Update index Fundamentals adding 2 PD blocks.md

---

content/fundamentals/sprints/2/day-plan/index.md

Week(s): 2
Adding the two exercises for this day: Slack and Spreadsheet
@SallyMcGrath

Update Fundamentals week 2 with PD blocks.md

---

content/fundamentals/prep/index.md

Week(s): Prep
This is adding the block of Child care, that has a link to the policy and the form to request it
@SallyMcGrath

Update index with Childcare expense block for Fundamentals prep.md

---

assets/styles/04-components/objectives.scss

so checkbox is clickable
fixes #47

extend label left edge under checkbox

---

content/blocks/backlog/index.md

Week(s): Prep
Underscores look a bit messy - instead, use different captions from node identifiers.

Use spaces not underscores in flowchart

---

content/blocks/retro/index.md
content/fundamentals/blocks/ship-it-requirements/index.md
content/fundamentals/sprints/1/prep/index.md
content/guides/deployment-netlify/another-site/index.md

Fundamentals sprint 1 copy edits

---

content/fundamentals/blocks/user-stories/index.md

Week(s): 1
* We don't really turn in coursework anymore, rephrase.
* Remove spurious 'Discover requirements'

Copy edits in user stories

---

.github/workflows/nightly-deploy.yml

The netlify action doesn't seem to work.

Use curl rather than netlify action

---

layouts/_default/_markup/render-codeblock-mermaid.html.html

Module: all
Week(s): all
fixes #96

reset mermaid diagram heights

---

layouts/_default/_markup/render-link.html

I added whitespace eaters and started the anchor on the same line as the end of the logic
fixes #60

fix for spurious whitespace -- somewhere in here there was a space

---

layouts/partials/time.html

and got time without its property
was showing whole map instead of time value

screwed up a merge somewhere

---

assets/styles/04-components/page-header.scss
assets/styles/layout/header.scss
layouts/partials/page-header.html

I will go and prune out old branches as well as things are moving fast this week and we can't really have loads of tiny style differences hanging around

cleaning up merge mistakes

---

content/fundamentals/sprints/3/day-plan/index.md

Week(s): 3
Adding the Fundamentals project presentation for 40 min. Another exercise will be added soon.

Update index FUN 3 Day - Blocky presentation.md

---

content/induction/day-plan/index.md

Module: Induction
Week(s): N/A
adding the presentation for induction (it's a PPT but with exercises to be done)

Update Induction index with PD link.md

---

README.md
config.toml
layouts/partials/block/data.html
layouts/partials/block/issue.html
layouts/partials/block/pd.html
layouts/partials/block/readme.html
layouts/partials/byline.html
layouts/partials/issues.html
layouts/partials/lastmod.html
layouts/partials/objectives/parsed.html

I can't push to Daniel's fork so I've checked out the pr and opened a new one to main...
That is almost certainly the wrong thing to do! Don't look at me; I'm monstrous.
This does everything #89 does but just once, in the data.html partial where we construct the resource already. 
It's worth noting adding auth like this raises the barrier to entry, as to locally build you now need a github token (and I guess to be part of the CYF org). It would be nice to extend this at some point to a toggle so interested parties can build without these steps.

Rework GitHub API interactions (moved from fork)

---

assets/styles/03-elements/misc-phrasing.scss

It's not super clear right now from styling these are clickable

Make cursor into hand when hovering over summary

---

layouts/shortcodes/tabs.html

we were markdownifying everything, so creating formatted strings of our code
I use the royal we here...

fix youtube being markdownified

---

assets/styles/02-variables/colors.scss
layouts/_default/_markup/render-codeblock-js.html
layouts/_default/_markup/render-codeblock-mermaid.html.html
layouts/_default/baseof.html
layouts/partials/block/youtube.html
layouts/partials/foot.html
layouts/partials/module-tabs.html
layouts/partials/scripts.html
layouts/partials/search.html
layouts/shortcodes/tabs.html
layouts/shortcodes/youtube.html

- reduce calls to scripts by moving them into a single aprtial called on baseof and setting them based on page store
- fix contrast on pop color as it had drifted below 4.5 on 1rem

performance audit, mini

---

layouts/partials/block/youtube.html
layouts/shortcodes/youtube.html

this is actually obviously the right thing to do but clearly I love to WET
this means we should write all our coolest funnest components and then invoke them from shortcodes or codefences to use them in markdown

invoke youtube partial from youtube shortcode

---

content/fundamentals/blocks/cyf-blocks-iteration/index.md
content/fundamentals/blocks/ship-it-iteration/index.md
content/fundamentals/sprints/1/prep/index.md
content/guides/code-style-guide/index.md

Week(s): 2
Previously this block was a copy of the Requirements content, which is not what the trainees should be doing.
This is based on the content in
https://syllabus.codeyourfuture.io/fundamentals/week-2/session#step-by-step but slightly reworked.
Fixes #78
@SallyMcGrath @gregdyke

Add Fundamentals Iteration: Ship It content

---

content/fundamentals/sprints/1/prep/index.md

I have added some input from German around stuff we should ask them to do. I don't think this interfers in the overall time
Week(s): 1
Adding input from German about Linkedin, Gmail and Slack.
I have also added full stop on every bullet point, since half of them had it and half didn't.

Update index of FUN S1 PREP.md

---

assets/styles/03-elements/buttons.scss
assets/styles/03-elements/misc-phrasing.scss
assets/styles/04-components/objectives.scss
assets/styles/04-components/tabs.scss
content/blocks/energiser/index.md
content/fundamentals/blocks/goals/index.md
content/fundamentals/blocks/ship-it-requirements/index.md
content/fundamentals/prep/index.md
content/fundamentals/sprints/1/prep/index.md
layouts/_default/_markup/render-link.html

Misc copy edits

---

layouts/_default/_markup/render-codeblock-objectives.html

we renamed all these but missed this call

missed this link from refactor of blocks

---

content/html-css/sprints/1/day-plan/index.md

Module: HTML/CSS
Week(s): 1
update day schedule with PD content

Update index HTML S1 Day PD.md

---

content/html-css/sprints/1/prep/index.md

Module: HTML/CSS
Week(s): 1
Adding links to PD Prep

Update HTMLCSS S1 Prep with PD links.md

---

content/html-css/sprints/2/prep/index.md

Module: HTML
Week(s): 2
adding the link to PD prep for HTML

Update index HTML W2 Prep.md

---

content/html-css/sprints/2/day-plan/index.md

Module: HTML
Week(s): 2
adding link to the PD content

Update index HTML W2 day content PD.md

---

content/html-css/sprints/2/day-plan/index.md

Module: HTML
Week(s): 2
correcting my missing "

Update index correcting ".md

---

content/html-css/sprints/3/prep/index.md

Module: HTML
Week(s): 3
Adding PD prep

Update index HTML W3 PD Prep.md

---

content/html-css/sprints/3/day-plan/index.md

Update index HTML W3 PD Day.md

---

content/html-css/sprints/4/prep/index.md

Module: HTML
Week(s): 4
adding prep content

Update index PD HTML W4 Prep content.md

---

content/js1/sprints/3/prep/index.md

Module: JS1
Week(s): 3
adding PD prep

Update index JS1 S3 PD Prep.md

---

content/html-css/prep/index.md

Module: HTML CSS
Week(s): overall prep
pretty light for this as they have Induction day before it. Just putting a guide through to the sprint views

Content: module prep page

---

content/js1/sprints/1/day-plan/index.md

Module: JS1
Week(s): 1
adding PD content for day plan

Update index JS1 W1 PD Content Day-plan.md

---

content/js1/sprints/3/day-plan/index.md

Module: JS1
Week(s): 3
adding day plan PD content

Update index JS1 S3 Day Plan PD.md

---

content/js1/sprints/4/prep/index.md

Module: JS1
Week(s): 4
adding pd prep

Update index JS1 S4 PD Prep.md

---

content/js1/sprints/1/prep/index.md

Module: JS1 
Week(s): 1
adding PD prep

Update index JS1 S1 PD prep.md

---

.github/ISSUE_TEMPLATE/module-rewrite.md

add module template

---

.github/ISSUE_TEMPLATE/module-rewrite.md

tidy the template

---

.github/ISSUE_TEMPLATE/module-rewrite.md

add an alternation to the prep section

---

content/js2/sprints/1/prep/index.md

Update index JS2 S1 Prep PD.md

---

content/js3/sprints/1/prep/index.md

Module: JS3
Week(s): 1
adding link to PD content

Update index JS3 S1 Prep PD.md

---

content/induction/blocks/next-steps/index.md

Improve the next steps section before the transition into the HTML & CSS module.
Module: Induction
Week(s): 1

Improve next steps

---

content/js1/sprints/1/prep/index.md

Goes hand-in-hand with review comments I've left on https://github.com/CodeYourFuture/curriculum/pull/18

Edits to JS1W1 rewrite

---

.github/ISSUE_TEMPLATE/module-rewrite.md

add extra checkpoints for different sections

---

content/js3/sprints/2/day-plan/index.md

Module: JS3
Week(s): 2
updating PD content

Update index JS3 S2 Day PD.md

---

content/js3/sprints/2/prep/index.md

Module: JS3
Week(s): 2
updating PD content

Update index JS3 S2 PD Prep.md

---

content/js3/sprints/1/day-plan/index.md

Update index JS3 W1 Day Plan PD.md

---

content/blocks/retro/index.md
content/html-css/blocks/what-are-forms/index.md
content/html-css/sprints/3/day-plan/index.md
content/html-css/sprints/3/prep/index.md

Module: HTML
Week(s): 3
Adding the prep - day plan to come, but opening this now for you to look at
I ended up taking a couple of videos of forms sessions and turning them into a question block like the previous weeks, but this time I included trainee answers as well. I also included some practice exercises.
Because this is mainly from real conversations, it's not as tight - but happy to take edits pls pls
Couldn't really find anything in our previous page that wasn't in the MDN forms module so just linked out to it.
Also used that video, which again is incredibly similar to all the lectures I've seen on this at CYF. 
Workshop will be the github search form exercise from the previous syllabus, coming up
Main coursework is Form Controls, which is already done

draft prep

---

content/induction/sprints/1/day-plan/index.md

Module: Induction
Week(s):1
Adding an extra 10 min exercise to identify the general availability of the cohort so that they can create their pairs with similar availability.
This is part of a bigger piece of getting them to plan their life as a developer.

Update index induction Weekly Availability exercise.md

---

content/js2/sprints/1/day-plan/index.md

Update index JS2 S1 Day PD.md

---

content/js3/sprints/3/prep/index.md

Module: JS3
Week(s): 3
add PD content

Update index JS3 S3 Prep PD.md

---

content/js3/sprints/3/day-plan/index.md

Update index JS3 S3 Day PD.md

---

content/js1/blocks/repl/index.md
content/js1/blocks/scripts/index.md

Module: JS1 
Week(s):1
#249 
Fix the introduction of statements and declarations in week 1 of JavaScript.

Fix introduction of statements and expressions

---

content/js3/sprints/4/prep/index.md

Module:JS3
Week(s): 4
update PD content

Update index JS3 S4 Prep PD.md

---

content/js3/sprints/4/day-plan/index.md

Module: JS3
Week(s): 4
update PD content

Update index JS3 S4 Day PD.md

---

content/blocks/study-45/index.md
content/html-css/_index.md
content/html-css/blocks/what-are-components/index.md
content/html-css/prep/index.md
content/html-css/sprints/4/day-plan/index.md
content/html-css/sprints/4/prep/index.md

Module: HTML
Week(s): 4
w4, which previously was basically empty, now has a little workshop on components and spends some more time practising Git in class.  This git exercise expects several prior activities with merging stuff that isn't actual code to have happened in the previous 7 weeks.
The in-class git and documentation practice replaces the previous in-class practice of shipping to Netlify, as we do that in ITD and FUN now 
Only 135 minutes of study group as the PD exercises take up almost the whole morning, which we might need to push back on.

Content: HTML W4  - components

---

content/databases/_index.md
content/final-projects/_index.md
content/js1/_index.md
content/js2/_index.md
content/js3/_index.md
content/node/_index.md
content/react/_index.md

Content: add coming soon banners to upcoming modules

---

content/js1/sprints/1/day-plan/index.md
content/js1/sprints/1/prep/index.md
content/js1/sprints/2/day-plan/index.md
content/js1/sprints/2/prep/index.md
content/js1/sprints/3/day-plan/index.md
content/js1/sprints/3/prep/index.md

Module: JS1
Week(s): 1 2 3
The paths were outdated from before the rework of block data
I guess I'm hallucinating again that I already did this...
I filled in an example day plan too but I presume Mitch will overrwrite this ASAP
@illicitonion

Bugfix replace wrong paths and names Js1/2 +

---

content/fundamentals/sprints/3/prep/index.md
content/fundamentals/success/index.md

Week(s): 4
Now we understand what the success view is, we can put the old graduation criteria on this page
I've put the direction to apply as coursework on w4 https://github.com/CodeYourFuture/Course-Fundamentals/issues/28
Fixes #84

Content: integrate graduation criteria

---

netlify/functions/clone.ts
netlify/helpers/github.ts
package-lock.json
package.json

Minor naming/scoping clean-ups

Code review suggestions

---

content/js1/sprints/1/day-plan/index.md

link to git cli workshop

---

content/js1/sprints/3/day-plan/index.md

update week 3 day plan

---

content/js1/sprints/4/day-plan/index.md

update day-plan for week 4

---

assets/scripts/app.js

Prevent scroll when closing hamburger menu

---

content/induction/sprints/1/day-plan/index.md

Module: Induction
Week(s): 1
the induction video was missing from induction day and there's one starting tomorrow

add missing video

---

layouts/partials/block/pullreq.html

Handle empty PR response by hiding component

---

content/js1/blocks/parameters/index.md

Module: JS1
Week(s): W2
Minor copy edits.

Minor copy edits

---

content/blocks/lunch/index.md

Adding responsibility clarity to this task
Module: All modules
Week(s): Every week
I have added the responsibility information on the lunch block, so it is clear everyone should help with every task.

Update index lunch.md

---

content/js2/sprints/4/prep/index.md

Module: JS2
Week(s): 4
Adding link to PD prep work
@LaraHuzjan

Update JS2 S4 Prep PD content.md

---

content/js2/sprints/4/day-plan/index.md

Module: JS2
Week(s): 4
Adding the Ball Point Game, which was agreed with @Dedekind561 to NOT use PD hours AND PD content (Public speaking / Circle of influence)

Update JS2 S4 PD Content + Ball Point Game.md

---

layouts/partials/block/pd.html

Fix PD block times

---

content/js2/sprints/2/day-plan/index.md

Module: JS2
Week(s): S2
Update Js2 S2 Day PD

Update Js2 S2 Day PD.md

---

content/js2/sprints/2/prep/index.md

Module: JS2
Week(s): 2
Update JS2 S2 Prep PD

Update JS2 S2 Prep PD.md

---

content/js2/sprints/3/prep/index.md

Module: JS2
Week(s): 3
Update index JS2 S3 PD Prep

Update index JS2 S3 PD Prep.md

---

content/js2/sprints/3/day-plan/index.md

Module: JS2
Week(s): 3
Update index JS2 S3 PD Day plan

Update index JS2 S3 PD Day plan.md

---

content/js1/blocks/assertions/index.md

use template literals for assertions

---

content/js1/sprints/1/day-plan/index.md

point to js1 week 1 evaluation

---

content/portfolio/sprints/1/backlog/index.md
content/portfolio/sprints/2/backlog/index.md
content/portfolio/sprints/3/backlog/index.md
content/portfolio/sprints/4/backlog/index.md

Module: Portfolio
Week(s): 1-4 backlog

Fix: backlog links

---

content/databases/sprints/4/day-plan/index.md
content/html-css/sprints/4/day-plan/index.md
content/js1/sprints/4/day-plan/index.md
content/js2/sprints/4/day-plan/index.md
content/js3/sprints/4/day-plan/index.md
content/node/sprints/4/day-plan/index.md
content/react/sprints/4/day-plan/index.md

The 15 minute time will show up once this is merged: https://github.com/CodeYourFuture/curriculum/pull/354
Module: All modules
Week(s): 4

point to check-in progress blocks in the day plans

---

layouts/partials/block/issue.html

fix time for issue block on day plan

---

content/portfolio/sprints/1/prep/index.md

Update index PR Sprint 1 Portfolio Module.md

---

content/portfolio/sprints/1/day-plan/index.md

Module: Portfolio
Week(s): 1
Added:
- module goal discussion
- smart goals discussion
- brought back the content of "starting a project" (requirements, data, user interface, etc)

Update index Portfolio Sprint 1.md

---

content/js2/_index.md

ronseal
Module: JS2
Week(s): 1-4

add hatching chick emoji to js2

---

content/js1/blocks/percentages/index.md
content/js1/blocks/return/index.md

Module: JS1
Week(s): 2
While reading through the new content (I'm trying to catch up again), I spotted some issues:
- In the Percentages section, there's a very abrupt change from explanatory content to (what I assume is) practice "exercises". I've added a bit more context and reworded to be a bit less maths-y
- In the Returning from a function section, I thought it was a bit odd to show the code snippet directly returning the expression first, instead of returning the variable that trainees would have already seen. So I switched those around
- At the end of the Returning from a function section, I spotted a bug in the code snippets that show logging of the output (return statements missing). I also added an example of what the output should be.
I'm happy to discuss any changes to …

JS1 Week 2 tweaks/improvements

---

content/portfolio/sprints/3/day-plan/index.md

Module: Portfolio
Week(s): S3
- [x ] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [ x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
Added demo + employability blocks
Moved retro to earlier, so they have a team retro (maybe we need a different block explaining it, since it is per team?)

Update index Portfolio S3 Day.md

---

content/portfolio/sprints/2/day-plan/index.md

Module:
Week(s):
- [x ] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)
Added employability energiser, planning black
Removed speaker and retrospective (these will be on week 3 and 5)

Update index Portfolio S2 Day Plan.md

---

content/portfolio/sprints/2/prep/index.md

Module: Portfolio
Week(s): 2
- [x ] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
Added a prep block for the week

Update index Portfolio S2 Prep.md

---

content/guides/contributing/minutes/index.md

Module: N/A
Week(s): N/A
Minutes for Tech Ed Syllabus team meeting on 2023-11-09

Adds minutes for 2023-11-09

---

content/js3/sprints/1/day-plan/index.md

Module: JS3
Week(s): 1
- team project in the morning
- components workshop in the afternoon
- rest of the time is study group
- dumped the retro for this session as no one will get to it

JS3 1 day plan

---

content/js1/blocks/assertions/index.md

testing a patch - it seems likely the highlight lines is wrong?
Module: js1
Week(s): 3 PREP

js1-3 formatting fail

---

content/js2/blocks/check-progress/index.md
content/js2/blocks/update/index.md

Module:JS2 
Week(s):Week3 prep

fixed character calculation

---

content/js3/sprints/2/day-plan/index.md

Module: JS3
Week(s): 2
This is the day plan for JS3 sprint 2. Prep is not here yet, I just need to check again with Mitch before embarking on it.
The majority of the day is for TV show project and coursework. We do a very small workshop on planning code.

day plan for JS3 - 2

---

content/js2/success/index.md
content/js3/success/index.md
content/node/success/index.md
content/react/success/index.md

Module: JS2, JS3, React, Node
Week(s): 4
replacing the basic success views which were empty for some reason
fixing my formatting fails from my minor panic as I couldn't build the main (it has suddenly become UNBEARABLY UNUSABLY slow?)

fix formatting, add missing

---

content/react/sprints/4/day-plan/index.md

Module: React
Week(s): 4
Update index React S4 PD Day Plan

Update index React S4 PD Day Plan.md

---

content/react/sprints/4/prep/index.md

Module: React
Week(s): 4
Update index React S4 PD Prep

Update index React S4 PD Prep.md

---

content/react/sprints/1/prep/index.md

Module: React
Week(s): 1
Update index React S1 PD Prep

Update index React S1 PD Prep.md

---

content/react/sprints/1/day-plan/index.md

Module: React
Week(s): 1
Update index React S1 PD Day Plan

Update index React S1 PD Day Plan.md

---

content/node/sprints/1/day-plan/index.md

Module: Node
Week(s): 1
Update index Node S1 PD Day Plan

Update index Node S1 PD Day Plan.md

---

content/html-css/sprints/1/day-plan/index.md

Addresses #308
Module: HTML
Week(s): 1
Fixes #308

add time to devtools workshop

---

content/js3/blocks/re-rendering-ui/index.md
static/filterFilms.html

Module: JS3
Week(s): 2
replacing the forEach in the card example with a much preferable ...cards

Copyedits JS3 - 2 replace foreach with spread array

---

content/node/sprints/4/prep/index.md

Module: Node
Week(s): 4
Update index Node S4 PD Prep

Update index Node S4 PD Prep.md

---

content/react/sprints/3/prep/index.md

Module: React
Week(s): 3
Update index React S3 PD Prep

Update index React S3 PD Prep.md

---

layouts/partials/scripts.html

Module: all
Week(s): all
remove codemirror script as we disabled the render hook and it's trashing performance once the sw is also rm
related to #439  and #427

Bugfix : rm codemirror script

---

config/issues-are-cached-and-incomplete/config.toml

Implement dev mode for faster iteration

---

content/en/react/sprints/2/day-plan/index.md

Module: React
Week(s): 2
Update index React S2 PD Day Plan

Update index React S2 PD Day Plan.md

---

content/en/react/sprints/2/prep/index.md

Module: React 
Week(s): 2
Update index React S2 PD Prep

Update index React S2 PD Prep.md

---

content/en/databases/sprints/1/prep/index.md

Module: Databases
Week(s): 1
Databases S1 PD Prep

Update index Databases S1 PD Prep.md

---

content/en/databases/sprints/1/day-plan/index.md

Module: Databases
Week(s): 1
Databases S1 PD Day Plan

Update index Databases S1 PD Day Plan.md

---

content/en/node/sprints/2/prep/index.md

Module: Node
Week(s): 2
Update index Node S2 PD Prep

Update index Node S2 PD Prep.md

---

content/en/node/sprints/2/day-plan/index.md

Module: Node
Week(s): 2
Update index Node S2 PD Day Plan

Update index Node S2 PD Day Plan.md

---

content/en/node/sprints/3/prep/index.md

Module: Node
Week(s): 3
Update index Node S3 PD Prep

Update index Node S3 PD Prep.md

---

content/en/node/sprints/3/day-plan/index.md

Module: Node
Week(s): 3
Update index Node S3 PD Day Plan

Update index Node S3 PD Day Plan.md

---

content/en/databases/sprints/3/prep/index.md

Module: Databases
Week(s): 3
Update index Databases S3 PD Prep

Update index Databases S3 PD Prep.md

---

content/en/databases/sprints/3/day-plan/index.md

Module: Databases
Week(s): 3
Update index Databases S3 PD Day Plan

Update index Databases S3 PD Day Plan.md

---

content/en/js3/blocks/components/index.md
content/en/js3/blocks/composing-elements/index.md
content/en/js3/blocks/data-ui/index.md
content/en/js3/blocks/now-showing/index.md
content/en/js3/blocks/one-to-one/index.md
content/en/js3/blocks/using-map/index.md
content/en/js3/sprints/1/prep/index.md
content/js3/blocks/simplifying-element-creation/index.md

Module: JS3
Week(s): 1
The major piece here is separating out the "extract a component function" piece from the "use a template" tag piece (as well as to add an alternative refactoring for solving the same problem the template tag solves).
Otherwise, there are some minor misc copy edits.

Copy edits on JS3S1

---

content/en/the-launch/prep/index.md

Module: Launch
Week(s): S1
adding the Lancuh Sprint 1 prep

Update index Prep Launch S1.md

---

content/en/the-launch/prep/index.md
content/en/the-launch/sprints/1/backlog/index.md
content/en/the-launch/sprints/1/day-plan/index.md
content/en/the-launch/sprints/1/prep/index.md
content/en/the-launch/sprints/1/success/index.md
content/en/the-launch/sprints/2/backlog/index.md
content/en/the-launch/sprints/2/day-plan/index.md
content/en/the-launch/sprints/2/prep/index.md
content/en/the-launch/sprints/2/success/index.md
content/en/the-launch/sprints/3/backlog/index.md
content/en/the-launch/sprints/3/day-plan/index.md
content/en/the-launch/sprints/3/prep/index.md
content/en/the-launch/sprints/3/success/index.md
content/en/the-launch/sprints/4/backlog/index.md
content/en/the-launch/sprints/4/day-plan/index.md
content/en/the-launch/sprints/4/prep/index.md
content/en/the-launch/sprints/4/success/index.md
content/en/the-launch/success/index.md

ronseal
https://codeyourfuture.slack.com/archives/C012UUW69S8/p1703080536703619

rename all module-final-projects to the launch

---

content/en/js3/blocks/components/index.md
content/en/js3/blocks/composing-elements/index.md
content/en/js3/blocks/one-to-one/index.md
content/en/js3/blocks/simplifying-element-creation/index.md
content/en/js3/blocks/template-html/index.md
content/en/js3/sprints/1/prep/index.md

Module: JS3
Week(s): 1
Reading JS3 1 and the new revisions have some errors
I have fixed them up I think and also cut a bit more to simplify

Revise JS3 1 prep - template tags

---

layouts/_default/_markup/render-codeblock-mermaid.html.html
layouts/partials/block/readme.html

Module: all
Week(s): all, but check html-css/sprints/2/day-plan/#asking-questions to test
https://deploy-preview-481--cyf-curriculum.netlify.app/html-css/sprints/2/day-plan/#asking-questions
this fixes the unintentional chomping of newlines in decoded content, which may be a part of the issue with #411 
it doesn't address the mermaids being drawn as size 0 in hidden blocks - I just fixed this in passing while i was looking at something else so figured I'd contribute it

mermaid fix for readme issue

---

content/en/js3/blocks/asynchrony/index.md
content/en/js3/blocks/callbacks/index.md

Module: js3 
Week(s): 3
Just checking it loupe was definitely blocked on live before rm it

rm loupe embeds, which randomly block

---

assets/styles/04-components/tooltip.scss

Module: all
Week(s): all
Daniel pointed out he can't click on links in #484 
This was an error. I had disallowed pointer events for reasons I cannot now recall or reproduce.
Fixes #487

allow pointer events in tooltips

---

assets/styles/03-elements/misc-phrasing.scss

Module: all
Week(s): all
fixes #488

zero out margins inside summary

---

content/en/js3/_index.md
content/en/js3/blocks/async-await/index.md
content/en/js3/blocks/catch/index.md
content/en/js3/blocks/fetch-films/data.json
content/en/js3/blocks/fetch-films/filterFilms.html
content/en/js3/blocks/fetch-films/index.md
content/en/js3/blocks/finally/index.md
content/en/js3/blocks/promises/index.md
content/en/js3/blocks/then/index.md
content/en/js3/sprints/4/day-plan/index.md
content/en/js3/sprints/4/prep/index.md

Module: JS3
Week(s): 4
Completing the concept map from JS3-3 with the final parts on Promises, then, async/await, and try/catch. I brought filterFilms back from week 2 and updated it with a fetch as the last part.
Please do checkout this PR and edit directly as well as offering line edits. If we can simplify or reduce, let's do this!
I will go away and fix the horrible Mermaid in solo view bug after React is ported. For now just reload the page (sorry!!!)

JS3 Sprint 4 prep: Promises, then, async/await, try/catch, getFilms

---

assets/scripts/app.js
assets/scripts/dark-mode.js
layouts/_default/baseof.html
layouts/partials/foot.html
layouts/partials/scripts.html

Gets dark mode status from local storage, sets body class whenever the app.js is loaded

Fix dark mode status #158

---

content/en/databases/sprints/1/prep/index.md
content/en/html-css/sprints/3/day-plan/index.md
content/en/js1/sprints/1/prep/index.md
layouts/partials/block/local.html

And fix up the three references to blocks which don't exist.

Error on missing local blocks

---

content/en/the-launch/sprints/2/day-plan/index.md

Module: Launch
Week(s): 2
Launch S2 Day Plan info

Update index Launch S2 Dayplan.md

---

content/en/the-launch/sprints/4/prep/index.md

Module: Launch
Week(s): S4
Prep S4 Launch

Update index Prep Launch S4.md

---

content/en/the-launch/sprints/3/prep/index.md

Module: Launch
Week(s): 3
adding prep for Sprint 3 of Launch

Update index S3 Launch.md

---

content/en/the-launch/sprints/2/prep/index.md

Module: Launch
Week(s): 2
adding prep for Launch S2

Update index Prep S2 Launch.md

---

content/en/the-launch/sprints/3/day-plan/index.md

Module: launch
Week(s): 3
Day Plan for Launch S3

Update index S3 Launch Day Plan.md

---

content/en/the-launch/sprints/4/day-plan/index.md

Module: Launch
Week(s): S4
day plan s4 launch. Same content as S2 and S3 for now.

Update index DayPlan Launch S4.md

---

content/en/the-launch/sprints/2/day-plan/index.md

Module: Launch
Week(s): S2
Sprint 2 for Launch also didn't have the right timings, which was noticed on S3 and S4, so adding them now

Update index add timings.md

---

assets/scripts/alert-message.js
assets/scripts/app.js
layouts/partials/scripts.html

What does this change?
Module: all
Week(s): all
Checklist
I have read the [contributing guidelines](https://github.com/CodeYourFuture/curriculum/pull/CONTRIBUTING.MD)
I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
I have run my code to check it works
My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)
Description :
There was a console error regarding element is not defined for alerts on the view in app.js
Moved this to a seperated class and fixed adding event listeners …

Fix console error for alert (#503)

---

assets/scripts/alert-message.js
assets/scripts/app.js
layouts/partials/scripts.html

disentangling the various merges to check the build is actually ok (I think it is) Everything was failing overnight but I think it's just that issues were left with No response on the repos, in the end!

Fix console error for alert (#503) REOPEN

---

content/en/js1/success/index.md

Module: JS1
Week(s): Success
JS1 Pd success

Update index JS1 Pd success.md

---

content/en/induction/success/index.md

Module: Induction 
Week(s): Success
induction PD Success

Update index induction PD Success.md

---

content/en/html-css/success/index.md

Module: HTML
Week(s): Success
adding PD success

Update index adding PD success.md

---

content/en/js3/blocks/components/index.md

Module: JS3
Week(s): 1
`createFilmCard` should accept a template as an argument instead of directly querying the DOM inside the function itself.

parametrize createFilmCard with template

---

assets/styles/layout/menu.scss

Module: all
Week(s): all
Updated the overflows of the menu itself users can scroll down if needed when the mobile device is turned 90 degrees.
Added a width to the secondary menu
@SallyMcGrath, @sztupy

Update style of the hamburger menu (#478)

---

org-cyf/content/databases/sprints/2/day-plan/index.md

Update index PD Content SQL S2 day Pplan.md

---

org-cyf/content/databases/sprints/4/day-plan/index.md

Update index SQL S4 DB.md

---

LICENSE

this document got lost in the reorg.

restore licence doc

---

org-cyf/content/fundamentals/sprints/1/prep/index.md

Week(s): Sprint 1
substituting German's e-mail address with a generic one

Update index amending e-mail.md

---

org-cyf/content/databases/sprints/4/prep/index.md

Module: SLQ (Databases)
Week(s): 4
Update index SQL (Databases) S4 PD Prep.md

Update index SQL (Databases) S4 PD Prep.md

---

org-cyf/content/databases/sprints/2/prep/index.md

Module: SQL (Databases)
Week(s): 2
Update index SQL (Databases) S2 PD Prep.md

Update index SQL (Databases) S2 PD Prep.md

---

org-cyf/content/servers/sprints/4/day-plan/index.md

Module: Node (Servers)
Week(s): 4
Update index Node (Servers) S4 PD Day Plan.md

Update index Node (Servers) S4 PD Day Plan.md

---

org-cyf/content/servers/sprints/3/prep/index.md

Module: Node (Servers)
Week(s): 3
Update index Node (Servers) S3 PD Prep.md

Update index Node (Servers) S3 PD Prep.md

---

org-cyf/content/servers/sprints/1/day-plan/index.md
org-cyf/content/servers/sprints/2/day-plan/index.md
org-cyf/content/servers/sprints/3/day-plan/index.md
org-cyf/content/servers/sprints/4/day-plan/index.md

Module: Node / Servers
Week(s): 1 2 3 4 DAY PLANS
Connect the 4 servers workshops to the day plans and check they are rendering.
They are rendering. All these workshops could be revised and improved, of course! This ticket is just connecting the version 1s.
This is the final piece of #352  -- as cohorts are now approaching this module I would appreciate a merge

workshops for each servers dayplan

---

.github/pull_request_template.md

git pr template
Updating the pr template to remove giant warning and add new options for content/feature/locations

update template, rm warning, add areas

---

org-cyf/content/react/success/index.md

Module: React
Week(s): Module success PD
Update index React Module success PD.md

Update index React Module success PD.md

---

org-cyf/content/react/product/success/index.md
org-cyf/content/react/success/index.md

+ add module menu to module success
+ add product menu to product success
+ disentangle objectives
fixes #583

fix success links

---

org-cyf/content/servers/sprints/2/day-plan/index.md

Block/s
Update index Node(servers) S2 PD Day Plan.md

Update index Node(servers) S2 PD Day Plan.md

---

org-cyf/content/guides/contributing/minutes/index.md

Add minutes for 27/02/2024 global syllabus meeting

---

common-theme/assets/styles/04-components/card.scss
common-theme/assets/styles/04-components/map.scss
common-theme/assets/styles/04-components/page-header.scss
common-theme/assets/styles/layout/header.scss
common-theme/assets/styles/layout/menu.scss
common-theme/layouts/index.html
common-theme/layouts/partials/card.html
common-theme/layouts/partials/map.html
org-cyf/content/_index.md
org-cyf/content/databases/_index.md
org-cyf/content/fundamentals/_index.md
org-cyf/content/html-css/_index.md
org-cyf/content/induction/_index.md
org-cyf/content/js1/_index.md
org-cyf/content/js2/_index.md
org-cyf/content/js3/_index.md
org-cyf/content/portfolio/_index.md
org-cyf/content/react/_index.md
org-cyf/content/servers/_index.md
org-cyf/content/the-launch/_index.md

New home page
also touches index of each module, adding to extra menus
Addresses #611 
In our global syllabus meeting the matter of the home page was raised - two main problems were described:
1. It's not super clear where to start, so I have added a pointing hand and the text "start here" at the first module
2. Tracks, which may begin after JS3 and through which trainees may take different paths, were confusing, so I have grouped them in a way that will make it easier to add lots of tracks and then have trainees pick and mix them to get to the launch
I have styled this lightly as a map - we could go much further with this concept, including an svg path that snakes around the entire curriculum, but tbh that stuff takes ages so I haven't bothered doing it unless we think we need it.
I also …

New home page

---

org-cyf/content/the-launch/success/index.md

Module: Launch
Week(s): Module success

Update index updating Module Success Launch.md

---

org-cyf/content/guides/contributing/minutes/index.md

Add Tech Ed Syllabus Team minutes for 2024-03-26.
Block/s

Add minutes for 2024-03-26

---

.github/pull_request_template.md

This updates the PR template for the whole repo, with some helpful comments agreed in our call.

updated PR

---

common-content/en/activities/_index.md
common-content/en/activities/analogise/_index.md
common-content/en/activities/define-and-refine/_index.md
common-content/en/activities/in-your-own-words/_index.md
common-content/en/activities/play-computer/_index.md
common-content/en/activities/tell-me-the-target/_index.md
common-content/en/activities/where-is-the-code-running/_index.md
common-content/en/activities/which-line-is-it/_index.md

add some activities to handbook

---

org-cyf/content/js1/sprints/1/success/index.md

- Removes old LOs off JS1 sprint 1 success page

rm old objectives off js1 sprint 1 succes page

---

common-content/en/module/react/vite/index.md

Adds the missing install step to the instructions to set up React via the Vite wizard. It also adds some minor clarifications to how to use the Vite wizard.
Fixes https://github.com/CodeYourFuture/curriculum/issues/604
Block Type
@CodeYourFuture/global-syllabus 
@areebsattar (who raised the bug)

Fix React/Vite setup instructions by adding missing install step

---

.github/pull_request_template.md

Fixes some minor grammar errors in the PR template.
I also added a commit to attempt to further clarify the "Org Content?" question, but it's possible I've misunderstood, so happy to drop that.
Extending from https://github.com/CodeYourFuture/curriculum/pull/651
@SallyMcGrath

Fix grammar in PR template

---

common-content/en/blocks/setup-project-teams/index.md
org-cyf/content/databases/product/prep/index.md
org-cyf/content/databases/sprints/1/day-plan/index.md
org-cyf/content/databases/sprints/2/day-plan/index.md
org-cyf/content/react/product/prep/index.md

So far:
- Brings the db setup and initialisation workshop forward by one week
- Debug workshop goes to week 2 day plan
- Blockify team setup instructions as per the React module

Setup cohort for the Full Stack Assessment

---

org-cyf/content/databases/prep/index.md

Adds a missing step that trainees might get confused without.

Add instruction to restart terminal in order to get `psql` onto the path

---

org-cyf/content/databases/sprints/3/_index.md
org-cyf/content/databases/sprints/4/_index.md
org-cyf/content/js1/sprints/4/_index.md
org-cyf/content/js2/sprints/1/_index.md
org-cyf/content/js2/sprints/2/_index.md
org-cyf/content/js2/sprints/3/_index.md
org-cyf/content/js3/sprints/1/_index.md
org-cyf/content/js3/sprints/2/_index.md
org-cyf/content/js3/sprints/3/_index.md
org-cyf/content/js3/sprints/4/_index.md
org-cyf/content/portfolio/sprints/1/_index.md
org-cyf/content/portfolio/sprints/2/_index.md
org-cyf/content/portfolio/sprints/3/_index.md
org-cyf/content/react/sprints/1/_index.md
org-cyf/content/react/sprints/2/_index.md
org-cyf/content/react/sprints/3/_index.md
org-cyf/content/react/sprints/4/_index.md
org-cyf/content/servers/sprints/1/_index.md
org-cyf/content/servers/sprints/2/_index.md
org-cyf/content/servers/sprints/3/_index.md
org-cyf/content/servers/sprints/4/_index.md

A bunch of these got omitted or muddled around. The overview page now makes sense again.

Fix themes

---

org-cyf/content/how-our-curriculum-works/sprints/self-coordinate/backlog/index.md

Change backlog filter for self coordinate section

Reveal backlog issues for self coordinate sprint

---

org-cyf/content/how-our-curriculum-works/sprints/self-evaluate/backlog/index.md

point to self evaluate backlog issues

---

org-cyf/content/guides/contributing/minutes/index.md

Adds minutes for 2024-04-23
N/A

Add minutes for 2024-04-23

---

common-content/en/module/databases/communicating-with-db/index.md

fixed broken link to hotel.sql file in index.md

---

common-content/en/blocks/setup-project-teams/index.md

Need to reuse this setup across different modules

small change - removed the unnecessary link!

---

org-cyf-itp/content/piscine/_index.md
org-cyf-itp/content/piscine/sprints/1/_index.md
org-cyf-itp/content/piscine/sprints/1/day-plan/index.md
org-cyf-itp/content/piscine/sprints/1/prep/index.md
org-cyf-itp/content/piscine/sprints/2/day-plan/index.md
org-cyf-itp/content/piscine/sprints/3/day-plan/index.md
org-cyf-itp/tooling/netlify.toml

Piscine | Sprint: all | Prep 
rm erroneous HTML content

Content rm all content from piscine

---

common-content/en/blocks/local/index.md
common-theme/archetypes/backlog.md
common-theme/archetypes/blocks/index.md
common-theme/archetypes/day-plan.md
common-theme/archetypes/module-prep.md
common-theme/archetypes/module.md
common-theme/archetypes/prep.md
common-theme/archetypes/product-success.md
common-theme/layouts/partials/block/data.html
common-theme/layouts/partials/block/link.html
common-theme/layouts/partials/block/pullreq.html
tooling/create_module.sh

/blocks/local
Add a sample local block the archetypes can call TODO maybe make an archetypes repo on GitHub with all the stuff we might want like issues and PRs and images?
yep:
1. archetypes/ <== fixed em all up so when you run create_module you get a fully functioning sample module you can fill in.
2. tiny bugfix on pullreq block to make it work on prep view
3. tiny bugfix on data block to make slides work on latest hugo version as the "in" check stopped working TODO update hugo version on main curriculum deploy
Fixes #542 
Go to /tooling
run `./create_module.sh org-cyf Test`
expected result
```
Content "/Users/lim/CYF/Repos/curriculum/org-cyf/content/Test/_index.md" created
Content "/Users/lim/CYF/Repos/curriculum/org-cyf/content/Test/prep/index.md" created
Content …
```

Bugfix: archetypes

---

common-theme/assets/scripts/toggle-all-details.js

Use like this
```
{{ $toggleAll := resources.Get "scripts/toggle-all-details.js" | resources.Minify }}
<script type="module" src="{{ $toggleAll.RelPermalink }}" defer></script>
<toggle-all-details
><button slot="button" id="toggle-all-details" class="e-button">
toggle all
</button></toggle-all-details >
```
Test by adding this to a page like backlog where there are lists of details elements. 
Necessary for the port of CYF+, though arguably we should also make a custom js block available - might do that next
This is so pages like https://systems.codeyourfuture.io/versions/1-1-0/ can work

feature: toggle details web component

---

org-cyf-itp/content/how-our-curriculum-works/_index.md
org-cyf-itp/content/how-our-curriculum-works/sprints/self-evaluate/prep/index.md
org-cyf/content/how-our-curriculum-works/_index.md

[ITP how our curr works](https://deploy-preview-730--cyf-programming.netlify.app/how-our-curriculum-works/)
[Old curr how our curr works](https://deploy-preview-730--cyf-curriculum.netlify.app/how-our-curriculum-works/)

Publish how our curriculum works

---

content/employability/example-post/index-md.md

Automatically generated by Static CMS

Create Employability “example-post/index-md”

---

common-content/en/module/induction/viewing-files/index.md

Encourage trainees to google for help when they get stuck - this is important to emphasise, especially early on in the course.
Modifying some content in the induction module in common-content
Issue number: #790 
Module
@CodeYourFuture/itp-syllabus-team

Encourage trainees to google for help when they get stuck

---

common-theme/assets/scripts/multiple-choice.js
common-theme/assets/styles/02-variables/colors.scss
common-theme/assets/styles/03-elements/forms.scss
common-theme/assets/styles/states/good.scss
common-theme/layouts/partials/multiple-choice.html
common-theme/layouts/shortcodes/multiple-choice.html

In our call I said I would PR a simple quiz feature for us to start with so here is a quiz shortcode. In the future we could improve this and add different types of questions etc. For now, it's just this:
A partial that expects the following:
1. one question
2. a slice of possible answers
3. a matched slice of feedback for each answer
4. the index of the correct answer
This can be called directly, see comments, or inside markdown with a shortcode.
A shortcode that calls the above partial. Example usage:
```
{{<multiple-choice
question="What is the purpose of an energiser?"
answers="To get everyone engaged and ready to learn | To burn an hour of the morning | To upset everyone | To make everyone sleepy"
feedback="Right! The purpose of an energiser is to get everyone engaged and ready to …
```

Feature: quiz shortcode

---

org-cyf-guides/content/employability/job-search/_index.md

Automatically generated by Static CMS

Update Employability “job-search/_index”

---

org-cyf-guides/content/employability/github/_index.md

Automatically generated by Static CMS

Update Employability “github/_index”

---

org-cyf-guides/content/employability/learning/exercism/index.md

fixes broken exercism python link

fixes broken exercism python link

---

common-theme/assets/styles/04-components/page-footer.scss
common-theme/assets/styles/layout/footer.scss
common-theme/layouts/_default/baseof.html
common-theme/layouts/partials/page-footer.html
org-cyf-itd/content/blocks/step-2/instructions/index.md
org-cyf-itd/content/blocks/step-3/instructions/index.md
org-cyf-itd/content/blocks/step-4/instructions/index.md
org-cyf-itd/content/blocks/step-5/instructions/index.md
org-cyf-itd/content/blocks/step-6/acceptance/index.md
org-cyf-itd/content/blocks/step-6/extend/index.md
org-cyf-itd/content/blocks/step-6/instructions/index.md
org-cyf-itd/content/blocks/step-6/submission/index.md
org-cyf-itd/content/steps/four/index.md
org-cyf-itd/content/steps/one/index.md
org-cyf-itd/content/steps/six/index.md
org-cyf-itd/content/steps/three/index.md
org-cyf-itd/content/steps/two/index.md
org-cyf-itd/hugo.toml
org-cyf-theme/hugo.toml

1. add english test step
2. add description for popover on home page
3. add in section navigation between steps NOTE https://gohugo.io/methods/pages/prev/ "unexpected behaviour"

add missing step six, missing descriptions, missing section nav

---

common-content/en/module/js2/arrays/index.md
common-content/en/module/js2/grouping-data/index.md

Fixing minor typos in variable names in Grouping Data and Arrays sections.
Issue number: #856 

Fix variable names in Grouping Data and Arrays sections

---

common-content/en/module/how-our-curriculum-works/our-mission/index.md

This copies over the content from
https://docs.codeyourfuture.io/leaders/running-the-course/assessment/success-criteria with some modifications - specifically:
* Trying to describe _why_ we still teach the same things to people without right to work.
* Broading "in tech" to include roles like support desk
Fixes #927

Define outcomes as a good job in tech

---

common-content/en/module/js1/check-unix-os/index.md

We get this question a lot. Having an authoritative place to point to for explanation is useful.

Explain why we don't support Windows

---

org-cyf-itp/content/user-data/sprints/1/day-plan/index.md

Adds workshop recommendation to day plan 1
No

Adds recommended workshops day plan sprint 1

---

org-cyf-itp/content/user-data/sprints/3/day-plan/index.md

Adds workshop recommendations for User Data sprint 3

Adds workshop recommendations

---

org-cyf-itp/content/how-our-curriculum-works/sprints/self-coordinate/success/index.md
org-cyf-itp/content/how-our-curriculum-works/sprints/self-evaluate/success/index.md
org-cyf-itp/content/how-our-curriculum-works/success/index.md

1. rm some template language
2. added a few basic objectives -- please do improve them

915 How Our Curriculum Works success page is empty

---

common-content/en/energisers/introduce-yourself/index.md

Adds a new energizer activity where participants can practice introducing themselves. 
Suggested [here](https://github.com/CodeYourFuture/CYF-Workshops/pull/231/files#r1760917613)
No
No

Adds new elevator pitch as energiser

---

common-content/en/module/js1/repl/index.md
common-theme/assets/styles/04-components/note.scss
common-theme/layouts/_default/_markup/render-blockquote.html
org-cyf-itp/hugo.toml
org-cyf-theme/assets/custom-theme/02-variables/colors.scss

fixes #954 
but not exactly
https://github.com/CodeYourFuture/curriculum/issues/954#issuecomment-2363738878

954 Notes in tabs don't render properly

---

common-content/en/blocks/study-group/index.md

..whoops!
https://deploy-preview-972--cyf-programming.netlify.app/structuring-data/sprints/3/day-plan/#study-group

912 Study group exercises says to find learning objectives but there are none

---

common-content/en/energisers/18-and-unders/index.md

Moving CYF Docs content to our main curriculum
Module | Sprint | Page Type | **Block Type**

Create index for 18 under icebreaker.md

---

common-theme/layouts/_default/day-plan.html
org-cyf-itp/hugo.toml

Fixes #866 
I've just updated the values pulling through. You can test it by looking on netlify. I have to go and figure out how to pull this data out into a spreadsheet for Karen

866 Identify course correctly on register

---

common-content/en/module/induction/accounts/index.md
org-cyf-itp/content/user-data/prep/index.md

we need to clearly tell them to do this or we will be back to the days of sexydino69
Fixes #812
I think the rest can go, but we do need this

return accounts activity to prep

---

common-content/en/module/cloud/technical-writing/index.md
common-content/en/module/portfolio/criteria/index.md
common-content/en/module/the-launch/goals/index.md
common-content/en/module/the-launch/presentation/index.md
common-content/en/module/the-launch/readme/index.md
common-content/en/module/the-launch/tips/index.md
common-theme/layouts/_default/prep.html
org-cyf-launch/content/demo day/prep/index.md
org-cyf-tracks/content/cloud/product/prep/index.md
org-cyf-tracks/content/portfolio/prep/index.md
org-cyf-tracks/content/portfolio/sprints/1/prep/index.md
org-cyf-tracks/content/portfolio/sprints/2/prep/index.md
org-cyf-tracks/content/portfolio/sprints/3/prep/index.md
org-cyf-tracks/content/portfolio/sprints/4/prep/index.md
org-cyf-tracks/content/portfolio/sprints/5/prep/index.md

I added a test for blocks on the prep view.
As a non-solo view no longer makes sense on this view if we are requiring blocks to exist, I also removed the flip from single to solo view layout to [simplify this template](https://github.com/CodeYourFuture/curriculum/pull/993/files#diff-ea65ba7c4caa45ff9d530fe30dfbd686ddf475c220c98b3c61c9618aeb500097). 
Then I ran over and fixed the errors very lightly. I copied the launch content from the old syllabus. On the tracks I just added existing content because both these tracks need massive revision before they are run again so there's no point getting into this now.
I left the SDC fails as they arebecause those belong to @illicitonion and I know he is in active development on this and also wanted this test. 
However I will run over Migracode's …

772 Chore: Clean up 13 broken pages and add prep content test

---

org-cyf-itp/content/user-data/success/index.md

we really want them to reflect on their learning, so maybe we do something like this?

what about something like this

---

org-cyf-itp/content/how-this-works/sprints/self-coordinate/_index.md
org-cyf-itp/content/how-this-works/sprints/self-educate/_index.md
org-cyf-itp/content/how-this-works/sprints/self-evaluate/_index.md
org-cyf-itp/content/overview/_index.md

* Updating ITP overview description
* Updating to use active voice
* Adding themes to how-this-works sprints
---------

Updating ITP overview description (#1004)

---

org-cyf-sdc/content/complexity/prep/index.md
org-cyf-sdc/content/computers/prep/index.md
org-cyf-sdc/content/decomposition/prep/index.md
org-cyf-sdc/content/decomposition/sprints/4/prep/index.md
org-cyf-sdc/content/legacy/prep/index.md
org-cyf-sdc/content/logic/prep/index.md
org-cyf-sdc/content/logic/sprints/1/prep/index.md

This is currently failing CI builds.

Add placeholder blocks to WIP SDC

---

common-content/en/module/databases/databases-with-sheets/index.md
org-cyf-itp/content/user-data/sprints/3/prep/index.md

-  Removes Sheets content from backlog & prep in sprint 3.
- Changes the objectives to actually represent what's in this doc. The other 2 were objects that will be learnt in the coursework, so I've changes it to mention what they'll learn in the coursework.

Update ITP Google sheets objectives

---

common-theme/layouts/partials/head.html

increase 10ms to 250ms fade on critical/head css #996

I can't stand that fouc sorry

---

common-content/en/module/databases/databases-with-sheets/index.md

I've seen people think that columns are stored _separately_ from rows, rather than that each row contains properties - hopefully this wording makes that slightly harder to infer.

Slightly reword to differentiate rows vs columns

---

common-content/en/module/how-our-curriculum-works/calendar/index.md
org-cyf-itp/content/how-this-works/sprints/self-coordinate/prep/index.md

Added the calendar to how this works
Yeah I added a block. I made it separate as other orgs don't want our calendar. When we move all this into a module, probably this block would be locally overriden.

add calendar link to HTW

---

common-content/en/blocks/workshop/index.md
org-cyf-itp/content/data-groups/success/index.md

Updates the success criteria for the data groups module

Data groups success criteria

---

org-cyf-itd/content/blocks/workshop-prep/index.md

Updated the slack channel for ITD

Updated the Slack channel for ITd.md

---

org-cyf-itd/content/blocks/step-6/instructions/index.md

Updated the time the Duolingo practice test takes from 15 minutes to 45 minutes, and updated the time needed for the whole step from 20 minutes to 50 minutes

Updated Duolingo practice test time.md

---

common-theme/assets/styles/04-components/tooltip.scss

bumps tooltip to second layer
Fixes #1051

1051 Tooltips z-index behind tabs

---

common-content/en/blocks/prep-dir-tests/index.md
common-content/en/module/js2/arrays/index.md
common-content/en/module/js2/assembly/index.md
common-content/en/module/js2/grouping-data/index.md
common-content/en/module/js2/iteration/index.md
common-content/en/module/js2/mean/index.md
common-content/en/module/js2/median/index.md
common-content/en/module/js2/more-median-cases/index.md
common-content/en/module/js2/mutation/index.md
common-content/en/module/js2/reference/index.md
common-content/en/module/js2/side-effects/index.md
common-content/en/module/js2/summing/index.md
org-cyf-guides/content/employability/cvs/applicant-tracking-system/index.md
org-cyf-itp/content/data-groups/sprints/1/prep/index.md

Just a bunch of misc copy edits.
Yes - edits to a bunch of js2 blocks, and creating one new one (moving some content from an existing one).
Sprint - pulling in new block for moved content.

Copy edits to Data Groups Sprint 1

---

org-cyf-guides/content/pair-programming/index.md

This is a start bootstrapped from the contents of our existing pair programming backlog tickets, so we can link to it and improve it.

Add a pair programming guide

---

common-content/en/module/js3/applying-map/index.md
common-content/en/module/js3/components/index.md
common-content/en/module/js3/composing-elements/index.md
common-content/en/module/js3/data-ui/index.md
common-content/en/module/js3/now-showing/index.md
common-content/en/module/js3/one-to-one/index.md
common-content/en/module/js3/simplifying-element-creation/index.md
common-content/en/module/js3/single-datum/index.md
common-content/en/module/js3/template-html/index.md
common-content/en/module/js3/using-map/index.md
org-cyf-itp/content/data-flows/sprints/1/prep/index.md

* Fix up a bunch of the HTML and JS to actually be consistent across steps we claim are consistent.
* Some minor rewordings.
Yes - edits much of JS3, and adds a new block.
Sprint

Misc copy edits to data-flows sprint 1

---

org-cyf-itp/content/data-groups/success/index.md

* Add DOM as a top-level LO
* Small copy edits

Update Data Groups Success page

---

org-cyf-itp/content/user-data/sprints/3/prep/index.md

Remove backlog task from sprint 3  It's already in sprint 1.

---

org-cyf-itp/content/overview/_index.md

Add overview to front page to surface it
ronseal

add overview to front page!

---

common-content/en/module/js1/assembly/index.md

other people are using it -- let's not silently remove content when we've no need to -- this would silently break MCB
if we're going to have common content we need to preserve it -- if there are really significant rewrites that make old versions unusable it's probably time to make a new block not rewrite

return assembly

---

org-cyf-itd/content/blocks/step-1/acceptance/index.md
org-cyf-itd/content/blocks/step-1/extend/index.md
org-cyf-itd/content/blocks/step-1/instructions/index.md
org-cyf-itd/content/blocks/step-1/submission/index.md
org-cyf-itd/content/steps/one/index.md

Replaced ITD step one with a version rewritten from the ground up. The new step covers using AI to draft a cover letter. This solves the issue with the previous version which was that the course it linked to didn't work correctly and there wasn't a drop in replacment
Having a hard time with reducing the complexity of the writing- on five on Hhemingwayapp.com, and I've done everything it said to do. Open to ideas. May just be being silly.
No
No
Issue number: #957 
No
- [ x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writin …

Change the content of step one to new genai step

---

common-content/en/module/how-our-curriculum-works/overview/index.md

Reverts CodeYourFuture/curriculum#1127 whoops no i wanted v1 of these edits

Revert "Suggested edits to discuss"

---

common-theme/assets/styles/04-components/timeline.scss
common-theme/layouts/_default/module.html
org-cyf-itp/content/user-data/prep/index.md
org-cyf-sdc/content/tools/prep/index.md

PR 1 of 3
Fixes  https://github.com/CodeYourFuture/curriculum/issues/1105#issuecomment-2428695177
brings theme onto module index view

1105 Include more theme/heading information on index pages

---

common-content/en/module/js3/actually-re-rendering/index.md
common-content/en/module/js3/async-await/index.md
common-content/en/module/js3/asynchrony/index.md
common-content/en/module/js3/break-down/index.md
common-content/en/module/js3/callbacks/index.md
common-content/en/module/js3/capturing-events/index.md
common-content/en/module/js3/fetch-films/index.md
common-content/en/module/js3/fetching-data/index.md
common-content/en/module/js3/identifying-state/index.md
common-content/en/module/js3/introducing-new-state/index.md
common-content/en/module/js3/latency/index.md
common-content/en/module/js3/promises/index.md
common-content/en/module/js3/re-rendering/index.md
common-content/en/module/js3/reacting/index.md
common-content/en/module/js3/refactoring-to-state-and-render/index.md
common-content/en/module/js3/rendering-based-on-state/index.md
common-content/en/module/js3/then/index.md
common-content/en/module/js3/using-fetch/index.md
org-cyf-itp/content/data-flows/sprints/2/prep/index.md
org-cyf-itp/content/data-flows/sprints/3/prep/index.md
org-cyf-itp/content/data-flows/success/index.md

As well as a bunch of copy edits, a few non-trivial changes:
* Sprint 2's code didn't actually fully work in a bunch of ways. Add soem blocks and steps making sure we actually step through all the issues that come across in the code we're teaching. I'm consciously leaving this mostly as a worked example, rather than do-yourself exercises, because the trainees already have the TV Show project as an entire do-yourself exercise about the same topics.
* When working with promises, consistently tell people to save examples to files and run them, rather than run them in the repl. This is because if you execute these snippets in a repl you get printed out extra Promise values (because the repl prints out each evaluated expression), which makes it much harder to do things like "spot the …

Non-trivial tweaks to Data Flows sprints 2 and 3

---

common-theme/layouts/_default/sprint.html
common-theme/layouts/partials/page-footer.html

this didn't work when I tried it before, but there's obviously something wrong in my pages model because it works now, and this is a much much smaller change
I think I prefer this to #1143 as it's just much less upheaval. Thoughts @illicitonion?
Fixes #1058

1058 Page nav within a module doesn't see sprints

---

org-cyf-itd/content/blocks/help/index.md
org-cyf-itd/content/blocks/step-1/extend/index.md
org-cyf-itd/content/blocks/step-2/extend/index.md
org-cyf-itd/content/blocks/step-3/extend/index.md
org-cyf-itd/content/blocks/step-4/submission/index.md
org-cyf-itd/content/blocks/step-5/extend/index.md
org-cyf-itd/content/blocks/step-5/instructions/index.md
org-cyf-itd/content/blocks/step-5/submission/index.md
org-cyf-itd/content/blocks/step-6/extend/index.md
org-cyf-itd/content/blocks/step-6/instructions/index.md

final fixes from call with Karen

---

org-cyf-itd/content/blocks/step-1/acceptance/index.md

Acceptance critea
No
No
Issue number: N/A
ITD | Step 1
None in particular - I just don't want to self review

Fix oversight to make acceptance critera and description match

---

common-content/en/blocks/retro/index.md

Suggest retros in RetroTool not FigJam
Figma requires sign-up which is fiddly.
Fixes #1104.
Yes (though the video is actually a CYF video not really a common one).

Suggest retros in RetroTool not FigJam

---

README.md

docs: typos

---

common-content/en/energisers/confident-presenting/index.md

Adds morning warmup to practice power poses

---

common-theme/layouts/_default/backlog.html

Fixing cloning bug

---

README.md

Fix case of link

---

org-cyf-itp/assets/custom-scripts/reviews/common.mjs
org-cyf-itp/assets/custom-scripts/reviews/index.mjs

This avoids people having to click through and notice someone's already reviewing a PR.

PR dashboard: Identify PRs that already have a reviewer

---

common-theme/layouts/partials/block/issues-list-as-blocks.html

just that - looking into MCB fails

handle null labels - no filter on backlog

---

org-cyf-itp/content/guides/teaching/timeline/index.md

data flows was misaligned, and what about christmas

edits to ITP timeline based on feedback

---

common-content/en/module/js1/functions-workshop/index.md
common-content/en/module/js1/testing-workshop/index.md
common-content/en/module/js2/arrays-workshop/index.md
common-content/en/module/js2/objects-workshop/index.md
org-cyf-itp/content/data-groups/sprints/1/prep/index.md
org-cyf-itp/content/data-groups/sprints/2/prep/index.md
org-cyf-itp/content/structuring-data/sprints/1/prep/index.md
org-cyf-itp/content/structuring-data/sprints/3/prep/index.md

Adding workshop recordings on functions, testing, arrays and objects
Yes, adding a few new sections in common-content to contain both the YouTube link as well as code snippets that can be used as a starting point.
Issue number: #1257 
Sprint
@CodeYourFuture/itp-syllabus-team

Adding workshop recordings on functions, testing, arrays and objects

---

common-content/en/module/tools/binary-and-hexidecimal-numbers/index.md

Add reading about signed numbers / two's complement

Add reading about signed numbers / two's complement

---

org-cyf-itp/content/data-flows/success/index.md

Remove a stretch task - they're optional.
Replace a small piece of coursework with the TV Show project, and explicitly require linking to PRs showing they collaborated.
Data Flows Success

Update Data Flows success

---

org-cyf-itp/content/data-flows/success/index.md
org-cyf-itp/content/data-groups/success/index.md

I've slightly reduced the criteria for checks to make the step review quicker.
I've slightly reworded to make it clearer based on common mistakes I've seen.
I've added a tip to tell them to submit their step even if we are a bit behind with our reviews -- we never want to limit a trainee based on external circumstances if we don't have to
I've added a link to the place to submit their step
Data groups | Success 
Data flows | Success
@kfklein and @moneyinthesky please note these minor changes. Will you be able to update the step (I can do this if not)?

Content: slightly reduce criteria on ITP success steps

---

common-content/en/module/how-our-curriculum-works/classplanner/index.md
org-cyf-how-this-works/content/sprints/self-coordinate/prep/index.md

Describes classplanner and the point of it for teams
Links to planner
Fixes #1125
htw/classplanner
HTW | Self coordinate | Prep
@NJ-G

Content 1125 Add Class Planner to the 'How it works' info setup/onboarding module

---

org-cyf-itp/content/data-groups/sprints/1/day-plan/index.md
org-cyf-itp/content/data-groups/sprints/3/day-plan/index.md

Increases workshop focus on PD in module Data-Groups sprint 1 and 3
- removes Arrays and testing workshop from sprint 1
- adds interviewing practice to sprint 3

Increases workshop focus on PD in module Data-Groups

---

org-cyf-itp/content/data-flows/sprints/2/prep/index.md

Update index Data Flow - Sprint 2 - Prep with Gathering requirements prep
No
No
Sprint

Update index Data Flow - Sprint 2 - Prep.md

---

common-content/en/blocks/morning-orientation/index.md

It's a bit fiddly to get to otherwise.
This is absolutely a leaky abstraction / layering violation. But a really useful one.

Facilitator block links to success page

---

org-cyf-itp/assets/custom-scripts/reviews/common.mjs

Update PR dashboard to use Module-Onboarding

---

common-content/en/blocks/spaced-repetition/index.md
common-content/en/module/js3/internet/index.md

Fix YouTube embed
We don't chomp whitespace, so it ends up in the URL

Fix YouTube embed

---

org-cyf-guides/content/contributing/minutes/index.md

Syllabus team minutes for 2025-01-14

Add minutes for 2025-01-14

---

common-content/en/module/entry-tracks/development/index.md
common-content/en/module/piscine/backlog/index.md
common-content/en/module/piscine/demo/index.md
common-content/en/module/piscine/development/index.md
common-content/en/module/piscine/interviews/index.md
common-content/en/module/piscine/kickoff/index.md
common-content/en/module/piscine/programming-prereqs/index.md
common-content/en/module/piscine/solo-development/index.md
common-content/en/module/piscine/solo-project/index.md
common-theme/assets/styles/04-components/rubric.scss
org-cyf-launch/content/blocks/development-time/index.md
org-cyf-piscine/content/sprints/1/day-plan/index.md
org-cyf-piscine/content/sprints/1/success/index.md
org-cyf-piscine/content/sprints/2/day-plan/index.md
org-cyf-piscine/content/sprints/2/success/index.md
org-cyf-piscine/content/sprints/3/day-plan/index.md
org-cyf-piscine/content/sprints/3/success/index.md
org-cyf-piscine/content/sprints/4/day-plan/index.md
org-cyf-piscine/content/sprints/4/success/index.md

* Fold in actual projects
* Adjust some timings, LOs, etc to make day plans and success pages all look about right.

Final touches on Piscine

---

org-cyf-piscine/package-lock.json
org-cyf-piscine/package.json
tooling/netlify/functions/submission-created.js

* Fix comment
* Install googleapis in piscine 
This is required for the submission-created function.

Fix functions more

---

common-docs/content/common-theme/shortcodes/issue.md
common-theme/layouts/shortcodes/issue.html

This is so @40thieves can embed an issue in markdown
/shortcodes/issue
Docs here /common-theme/shortcodes/issue/

feature: issue shortcode

---

org-cyf-tracks/content/ai-essentials/prep/index.md

whoops
- wrong block - moved to right form

hotfix application form

---

org-cyf-tracks/content/ai-essentials/success/index.md
org-cyf-tracks/content/blocks/ai-essentials/prereqs/index.md

* Unify legacy requirements to be JS3 - this is what's in the application form.
* Success is success for the track, let's say that.
AI Essentials track

Minor tweaks to AI essentials track

---

common-content/en/blocks/demo/index.md
org-cyf-sdc/content/tools/sprints/1/day-plan/index.md
org-cyf-sdc/content/tools/sprints/2/day-plan/index.md
org-cyf-sdc/content/tools/sprints/3/day-plan/index.md
org-cyf-sdc/content/tools/sprints/4/day-plan/index.md

Note that the workshops are currently WIP placeholders from a branch, and also may change.
Currently I'm not attached to any of these workshops, nor to the study group time in the mornings.

Fill in SDC Tools day plans

---

common-content/en/module/js1/check-unix-os/index.md
org-cyf-itp/content/structuring-data/prep/index.md

At this stage in ITP, everyone _should_ be enrolled as a trainee.
This block is already present in the prep for SDC.

Re-add guidance about Windows laptops to ITP

---

org-cyf-tracks/content/ai-essentials/sprints/1/day-plan/index.md
org-cyf-tracks/content/ai-essentials/sprints/2/day-plan/index.md
org-cyf-tracks/content/ai-essentials/sprints/3/day-plan/index.md

I held off on this because we thought we might have to redo the day plan again (again) but it seems fine so will lock it in now.
These are just the issues made from before linked in the right places

update placeholders with issues for day plans

---

org-cyf-itd/content/blocks/step-0/instructions/index.md

Changing the timing of the Step 0 from 30 to 60 min long
Block Type

Update index - 30 to 60 min.md

---

org-cyf-itd/content/blocks/step-1/instructions/index.md

Changing the instruction time for cover letter (ITD Step 1) from 60 to 90 min 
Block Type

Update index Step 1 ITD - 60 to 90 min.md

---

org-cyf-itd/content/blocks/step-2/instructions/index.md

Change step 2 instructing from 90 to 120 min lenght
Block Type
- [x ] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [x ] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [x ] I have run my code to check it works
- [x ] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)

Update index - Step 2 ITD - 90 to 120 min.md

---

org-cyf-itd/content/blocks/step-4/instructions/index.md

Update step 4 from 240 min to 300 min
Block Type

Update index step 4 itd - 240-300.md

---

org-cyf-itd/content/blocks/step-3/instructions/index.md

Update step 3 ITD from 360 to 480 min.
Block Type

Update index step 3 itd. 360-480 min.md

---

common-content/en/module/decomposition/backend-limitations/index.md

@illicitonion I have removed the duplication of `to`  in this section. Could you please review and merge if happy?

Fix typo in backend limitations context section

---

org-cyf-itd/content/blocks/step-1/acceptance/index.md
org-cyf-itd/content/blocks/step-1/instructions/index.md
org-cyf-itd/content/blocks/step-1/submission/index.md

Improves requirements for step 1
No
No
Issue number: #1371
Yes - ITD Step 1
- [x ] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)
@ZacheeNiyokwizera @cjyuan

Clarify ITD Step 1

---

org-cyf-itd/content/steps/five/index.md
org-cyf-itd/content/steps/four/index.md
org-cyf-itd/content/steps/one/index.md
org-cyf-itd/content/steps/six/index.md
org-cyf-itd/content/steps/three/index.md
org-cyf-itd/content/steps/two/index.md

This doesn't rename all the blocks, which we should probably do at some point. (But we should probably name them to be semantically named rather than numerically named).

Add new step 1 to the list

---

org-cyf-sdc/content/decomposition/sprints/1/day-plan/index.md

Also includes https://github.com/CodeYourFuture/curriculum/pull/1399

Update SDC Decomposition 1 to workshop

---

org-cyf-guides/content/employability/interview/technical-interview-prep/_index.md

This was in the old syllabus and got a bit lost. This pulls in the old content pretty much verbatim and updates the markdown a bit.

Re-add technical interview guide

---

common-content/en/module/decomposition/classes-and-objects/index.md
common-content/en/module/decomposition/dataclasses/index.md
common-content/en/module/decomposition/enums/index.md
common-content/en/module/decomposition/generics/index.md
common-content/en/module/decomposition/inheritance/index.md
common-content/en/module/decomposition/methods/index.md
common-content/en/module/decomposition/type-checking-with-mypy/index.md
common-content/en/module/decomposition/type-guided-refactorings/index.md
common-content/en/module/decomposition/why-types/index.md
org-cyf-sdc/content/decomposition/sprints/4/_index.md
org-cyf-sdc/content/decomposition/sprints/4/prep/index.md

Adds a bunch of common content explaining things about types, and sets up the org-cyf-sdc sprint about them.
Adds a bunch of blocks.
Sets up a CYF SDC sprint.

SDC Decomposition Sprint 4

---

org-cyf-itp/content/welcome/success/index.md

Changing online to "if you region is running it online) so it's not a given
Module

Update Success - Welcome.md

---

common-content/en/module/onboarding/help/index.md

Updating the Help page to make it clear that everyone can get support in the first 5 weeks (except laptops)
Module

Update help - Welcome module.md

---

common-content/en/module/onboarding/steps/index.md

Adding the information about the importance of becoming a trainee + deadline

Update Onboarding step.md

---

common-content/en/module/onboarding/goals/index.md

Add information about having to enrol by week 6
I also bolded some information I thoug would be important to highlight and changed enroll to enrol.
Module

Update goals - Welcome Prep.md

---

common-content/en/blocks/working-with-others/index.md
org-cyf-itp/content/onboarding/sprints/2/day-plan/index.md

Adds a day-plan discussion about working with others.
Adds to Onboarding 2 day-plan

Add working with others discussion.

---

common-content/en/module/induction/working-locally/index.md

Replaced the existing photo diagram with a Mermaid diagram 
Issue number: #1436 
@illicitonion

Diagram replace with mermaid

---

legacy-curriculum-redirects/netlify.toml

A couple of people have told me about broken links with bad certs recently.

Set up redirects for syllabus. to curriculum.

---

org-cyf-launch/content/blocks/job-description/index.md

Amending this considering the new course
Block Type
- [x ] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend

Update index - new course update.md

---

common-content/en/module/business-analysis/business-requirements/index.md
common-content/en/module/business-analysis/presentation/index.md
common-content/en/module/business-analysis/swot/index.md
common-content/en/module/business-analysis/use-case/index.md

LOs should always be testable statements ("Compare X and Y" rather "Awareness of"), and should ~never start "Understand" :)

Improve some learning objectives

---

common-content/en/module/business-analysis/presentation/index.md

Change the presentation content
Module | Sprint | Page Type | **Block** Type

Update index - make presentation clear.md

---

org-cyf-guides/content/employability/cvs/applicant-tracking-system/index.md
org-cyf-guides/content/employability/cvs/cv-layout/index.md
org-cyf-guides/content/employability/cvs/working-through-sections/index.md

Amended information about how the ATS works. 
Added information about CV format and basic information to include. 
No
No
N/A
@illicitonion

Updated employability guides for ATS and CV

---

org-cyf-guides/content/virtual-class/index.md

Added section for online etiquette

minor addition for etiquette

---

common-content/en/module/business-analysis/review/index.md

Editing a typo in sprint-6/prep

---

common-content/en/module/tools/individual-shell-tools/index.md

Expands the introduction to tools of Unix.
No
N/a
Issue number: N/A
SDC | Sprint 1 |  MD
@illicitonion

add comments on pipes

---

org-cyf-itd/content/blocks/how-itd-works/what-is-itd/index.md

Ideally this would be driven from some shared config, but this is fiddly across the sites.

Update ITD frequency

---

common-content/en/module/business-analysis/new-use-case/index.md

Updating Day Plan for Day 5
Module | Sprint | Page Type | **Block Type**

Update Sprint 6 Day Plan

---

common-content/en/module/business-analysis/new-use-case/index.md
org-cyf-tracks/content/business-analysis/sprints/6/day-plan/index.md

Some more changes (spacing) but also timings on day plan
Module | Sprint | Page Type | **Block Type**
- [ x] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend

Changing day plan sprint 6 BA

---

common-content/en/blocks/discuss-behavioural-interviews/index.md
org-cyf-sdc/content/legacy/sprints/1/day-plan/index.md

I've added "Do a mock behavioural interview" to the backlog, this is a session to discuss that experience.

Add discussion of behavioural interviews

---

common-content/en/blocks/discuss-technical-interviews/index.md
org-cyf-sdc/content/complexity/sprints/1/day-plan/index.md

I've added "Do a mock technical interview" to the backlog, this is a session to discuss that experience.

Add discussion of technical interviews

---

org-cyf-theme/assets/custom-scripts/reviews/index.mjs
org-cyf-theme/layouts/_default/needs-review.html

This allows linking to a region-specific page, as well as filtering within the page.

Add region filter to PR list

---

org-cyf-itp/content/data-groups/sprints/1/_index.md
org-cyf-itp/content/data-groups/sprints/2/_index.md
org-cyf-itp/content/data-groups/sprints/3/_index.md
org-cyf-itp/content/onboarding/sprints/2/_index.md
org-cyf-itp/content/onboarding/sprints/3/_index.md
org-cyf-launch/content/sprints/1/_index.md
org-cyf-launch/content/sprints/2/_index.md
org-cyf-launch/content/sprints/3/_index.md
org-cyf-launch/content/sprints/4/_index.md
org-cyf-tracks/content/databases/sprints/1/_index.md
org-cyf-tracks/content/databases/sprints/2/_index.md
org-cyf-tracks/content/databases/sprints/3/_index.md
org-cyf-tracks/content/databases/sprints/4/_index.md
org-cyf-tracks/content/portfolio/sprints/1/_index.md
org-cyf-tracks/content/portfolio/sprints/2/_index.md
org-cyf-tracks/content/portfolio/sprints/3/_index.md
org-cyf-tracks/content/portfolio/sprints/4/_index.md
org-cyf-tracks/content/portfolio/sprints/5/_index.md
org-cyf-tracks/content/react/sprints/1/_index.md
org-cyf-tracks/content/react/sprints/2/_index.md
org-cyf-tracks/content/react/sprints/3/_index.md
org-cyf-tracks/content/react/sprints/4/_index.md
org-cyf-tracks/content/servers/sprints/1/_index.md
org-cyf-tracks/content/servers/sprints/2/_index.md
org-cyf-tracks/content/servers/sprints/3/_index.md
org-cyf-tracks/content/servers/sprints/4/_index.md

This was generated by running:
```bash
rg -l 'The plan for the week' | xargs sed -e 's#The plan for the week#The plan for the sprint#g' -i ''
```
Closes #836

Replace "week" with "sprint"
